
#include <uf.h>
#include <uf_obj.h>
#include <uf_ui.h>

//#include <NXOpen/Annotations.hxx>
//#include <NXOpen/Annotations_AngularDimension.hxx>
//#include <NXOpen/Annotations_AngularTolerance.hxx>
#include <NXOpen/Annotations_Annotation.hxx>
#include <NXOpen/Annotations_AnnotationManager.hxx>
//#include <NXOpen/Annotations_AppendedText.hxx>
//#include <NXOpen/Annotations_ArbitraryTarget.hxx>
//#include <NXOpen/Annotations_ArbitraryTargetData.hxx>
//#include <NXOpen/Annotations_ArcLengthDimension.hxx>
//#include <NXOpen/Annotations_AreaTarget.hxx>
//#include <NXOpen/Annotations_AssociatedObject.hxx>
//#include <NXOpen/Annotations_Associativity.hxx>
//#include <NXOpen/Annotations_BaselineDimension.hxx>
#include <NXOpen/Annotations_BaseSurfaceFinish.hxx>
#include <NXOpen/Annotations_BoltCircleCenterline.hxx>
//#include <NXOpen/Annotations_BusinessModifier.hxx>
//#include <NXOpen/Annotations_BusinessModifierCollection.hxx>
#include <NXOpen/Annotations_CenterMark.hxx>
#include <NXOpen/Annotations_Centerline2d.hxx>
#include <NXOpen/Annotations_CenterlineCollection.hxx>
//#include <NXOpen/Annotations_ChainDimension.hxx>
//#include <NXOpen/Annotations_ChamferDimension.hxx>
//#include <NXOpen/Annotations_ChamferDimensionPreferences.hxx>
#include <NXOpen/Annotations_CircularCenterline.hxx>
//#include <NXOpen/Annotations_CircularTarget.hxx>
//#include <NXOpen/Annotations_CircularTargetData.hxx>
//#include <NXOpen/Annotations_ConcentricCircleDimension.hxx>
//#include <NXOpen/Annotations_CustomerValueBusinessModifier.hxx>
//#include <NXOpen/Annotations_CustomSymbol.hxx>
//#include <NXOpen/Annotations_CustomSymbolCollection.hxx>
//#include <NXOpen/Annotations_CustomSymbolData.hxx>
//#include <NXOpen/Annotations_CustomSymbolTextData.hxx>
//#include <NXOpen/Annotations_CylindricalDimension.hxx>
//#include <NXOpen/Annotations_Datum.hxx>
//#include <NXOpen/Annotations_DatumData.hxx>
//#include <NXOpen/Annotations_DatumReference.hxx>
//#include <NXOpen/Annotations_DatumTarget.hxx>
//#include <NXOpen/Annotations_DatumTargetCollection.hxx>
//#include <NXOpen/Annotations_DatumTargetData.hxx>
//#include <NXOpen/Annotations_DiameterDimension.hxx>
//#include <NXOpen/Annotations_DiameterRadiusPreferences.hxx>
#include <NXOpen/Annotations_Dimension.hxx>
#include <NXOpen/Annotations_DimensionCollection.hxx>
//#include <NXOpen/Annotations_DimensionData.hxx>
//#include <NXOpen/Annotations_DimensionPreferences.hxx>
//#include <NXOpen/Annotations_DimensionSet.hxx>
//#include <NXOpen/Annotations_DimensionSetCollection.hxx>
#include <NXOpen/Display_SelPref.hxx>
#include <NXOpen/Display_SelPrefCollection.hxx>
//#include <NXOpen/Annotations_DraftingAid.hxx>
#include <NXOpen/Annotations_DraftingSurfaceFinish.hxx>
#include <NXOpen/Annotations_DraftingSurfaceFinishCollection.hxx>
//#include <NXOpen/Annotations_Fcf.hxx>
//#include <NXOpen/Annotations_FcfCollection.hxx>
//#include <NXOpen/Annotations_FcfData.hxx>
//#include <NXOpen/Annotations_FcfFrame.hxx>
//#include <NXOpen/Annotations_FcfFrameData.hxx>
//#include <NXOpen/Annotations_FoldedRadiusDimension.hxx>
#include <NXOpen/Annotations_Gdt.hxx>
#include <NXOpen/Annotations_GdtCollection.hxx>
//#include <NXOpen/Annotations_GdtDatumCollection.hxx>
//#include <NXOpen/Annotations_HoleDimension.hxx>
//#include <NXOpen/Annotations_HatchBuilder.hxx>
#include <NXOpen/Annotations_HatchCollection.hxx>
#include <NXOpen/Annotations_HatchFillSettingsBuilder.hxx>
//#include <NXOpen/Annotations_HatchStyleBuilder.hxx>
//#include <NXOpen/Annotations_HorizontalDimension.hxx>
//#include <NXOpen/Annotations_HorizontalOrdinateDimension.hxx>
//#include <NXOpen/Annotations_HorizontalOrdinateMargin.hxx>
//#include <NXOpen/Annotations_IAngularTolerance.hxx>
//#include <NXOpen/Annotations_IAppendedText.hxx>
//#include <NXOpen/Annotations_ICircularTarget.hxx>
//#include <NXOpen/Annotations_IContainer.hxx>
//#include <NXOpen/Annotations_IDatum.hxx>
//#include <NXOpen/Annotations_IDatumTarget.hxx>
#include <NXOpen/Annotations_IdSymbolCollection.hxx>
//#include <NXOpen/Annotations_IFcf.hxx>
//#include <NXOpen/Annotations_ILinearTolerance.hxx>
//#include <NXOpen/Annotations_ILineTarget.hxx>
#include <NXOpen/Annotations_IntersectionSymbol.hxx>
#include <NXOpen/Annotations_IntersectionSymbolCollection.hxx>
//#include <NXOpen/Annotations_IPmi.hxx>
//#include <NXOpen/Annotations_IPointTarget.hxx>
//#include <NXOpen/Annotations_IRectangularTarget.hxx>
#include <NXOpen/Annotations_Label.hxx>
#include <NXOpen/Annotations_LabelCollection.hxx>
//#include <NXOpen/Annotations_LabelData.hxx>
//#include <NXOpen/Annotations_LeaderBundle.hxx>
#include <NXOpen/Annotations_LetteringPreferences.hxx>
#include <NXOpen/Annotations_LineAndArrowPreferences.hxx>
#include <NXOpen/Annotations_LinearTolerance.hxx>
//#include <NXOpen/Annotations_LineTarget.hxx>
#include <NXOpen/Annotations_LineWeld.hxx>
//#include <NXOpen/Annotations_LineWeldData.hxx>
//#include <NXOpen/Annotations_LineWeldSideData.hxx>
//#include <NXOpen/Annotations_ListBusinessModifier.hxx>
//#include <NXOpen/Annotations_MajorAngularDimension.hxx>
//#include <NXOpen/Annotations_MasterCustomSymbol.hxx>
//#include <NXOpen/Annotations_MinorAngularDimension.hxx>
//#include <NXOpen/Annotations_NarrowDimensionPreferences.hxx>
#include <NXOpen/Annotations_Note.hxx>
//#include <NXOpen/Annotations_NoteBase.hxx>
#include <NXOpen/Annotations_NoteCollection.hxx>
//#include <NXOpen/Annotations_NoteData.hxx>
#include <NXOpen/Annotations_OffsetCenterPoint.hxx>
#include <NXOpen/Annotations_OffsetCenterPointCollection.hxx>
//#include <NXOpen/Annotations_OrdinateDimension.hxx>
//#include <NXOpen/Annotations_OrdinateDimensionPreferences.hxx>
//#include <NXOpen/Annotations_OrdinateMargin.hxx>
//#include <NXOpen/Annotations_OrdinateMarginCollection.hxx>
//#include <NXOpen/Annotations_OrdinateOriginDimension.hxx>
//#include <NXOpen/Annotations_ParallelDimension.hxx>
//#include <NXOpen/Annotations_PerpendicularDimension.hxx>
//#include <NXOpen/Annotations_PmiArcLengthDimension.hxx>
//#include <NXOpen/Annotations_PmiBaselineDimension.hxx>
//#include <NXOpen/Annotations_PmiChainDimension.hxx>
//#include <NXOpen/Annotations_PmiChamferDimension.hxx>
//#include <NXOpen/Annotations_PmiConcentricCircleDimension.hxx>
//#include <NXOpen/Annotations_PmiCustomSymbol.hxx>
//#include <NXOpen/Annotations_PmiCylindricalDimension.hxx>
//#include <NXOpen/Annotations_PmiData.hxx>
//#include <NXOpen/Annotations_PmiDiameterDimension.hxx>
//#include <NXOpen/Annotations_PmiFilter.hxx>
//#include <NXOpen/Annotations_PmiFilterByPart.hxx>
//#include <NXOpen/Annotations_PmiFilterByType.hxx>
//#include <NXOpen/Annotations_PmiFilterByView.hxx>
//#include <NXOpen/Annotations_PmiFilterCollection.hxx>
//#include <NXOpen/Annotations_PmiFoldedRadiusDimension.hxx>
//#include <NXOpen/Annotations_PmiHoleDimension.hxx>
//#include <NXOpen/Annotations_PmiHorizontalDimension.hxx>
//#include <NXOpen/Annotations_PmiHorizontalOrdinateDimension.hxx>
//#include <NXOpen/Annotations_PmiLabel.hxx>
//#include <NXOpen/Annotations_PmiLineWeld.hxx>
//#include <NXOpen/Annotations_PmiMajorAngularDimension.hxx>
//#include <NXOpen/Annotations_PmiMinorAngularDimension.hxx>
//#include <NXOpen/Annotations_PmiNote.hxx>
//#include <NXOpen/Annotations_PmiOrdinateOriginDimension.hxx>
//#include <NXOpen/Annotations_PmiParallelDimension.hxx>
//#include <NXOpen/Annotations_PmiPerpendicularDimension.hxx>
//#include <NXOpen/Annotations_PmiPreferences.hxx>
//#include <NXOpen/Annotations_PmiRadiusDimension.hxx>
//#include <NXOpen/Annotations_PmiVerticalDimension.hxx>
//#include <NXOpen/Annotations_PmiVerticalOrdinateDimension.hxx>
//#include <NXOpen/Annotations_PointTarget.hxx>
//#include <NXOpen/Annotations_RadiusDimension.hxx>
//#include <NXOpen/Annotations_RectangularTarget.hxx>
//#include <NXOpen/Annotations_RectangularTargetData.hxx>
//#include <NXOpen/Annotations_RevisionBusinessModifier.hxx>
//#include <NXOpen/Annotations_SafetyClassBusinessModifier.hxx>
//#include <NXOpen/Annotations_SimpleDraftingAid.hxx>
//#include <NXOpen/Annotations_SimpleDraftingAidPreferences.hxx>
#include <NXOpen/Annotations_SymbolPreferences.hxx>
#include <NXOpen/Annotations_SymmetricalCenterline.hxx>
//#include <NXOpen/Annotations_UnitsFormatPreferences.hxx>
//#include <NXOpen/Annotations_UrlBusinessModifier.hxx>
//#include <NXOpen/Annotations_UserSymbolPreferences.hxx>
//#include <NXOpen/Annotations_VerticalDimension.hxx>
//#include <NXOpen/Annotations_VerticalOrdinateDimension.hxx>
//#include <NXOpen/Annotations_VerticalOrdinateMargin.hxx>
//#include <NXOpen/Annotations_Weld.hxx>
#include <NXOpen/Annotations_WeldCollection.hxx>
//#include <NXOpen/Arc.hxx>
//#include <NXOpen/ArcCollection.hxx>
//#include <NXOpen/Assemblies_Arrangement.hxx>
//#include <NXOpen/Assemblies_ArrangementCollection.hxx>
#include <NXOpen/Assemblies_Component.hxx>
#include <NXOpen/Assemblies_ComponentAssembly.hxx>
#include <NXOpen/Assemblies_ComponentPattern.hxx>
#include <NXOpen/Assemblies_ComponentPatternCollection.hxx>
//#include <NXOpen/Assemblies_Explosion.hxx>
//#include <NXOpen/Assemblies_ExplosionCollection.hxx>
//#include <NXOpen/AutomaticTraceline.hxx>
//#include <NXOpen/Axis.hxx>
//#include <NXOpen/AxisCollection.hxx>
#include <NXOpen/BasePart.hxx>
//#include <NXOpen/BaseSession.hxx>
//#include <NXOpen/Body.hxx>
//#include <NXOpen/BodyCollection.hxx>
#include <NXOpen/Builder.hxx>
//#include <NXOpen/CAE_AfuData.hxx>
//#include <NXOpen/CAE_AfuManager.hxx>
//#include <NXOpen/CAE_CAEBody.hxx>
//#include <NXOpen/CAE_CAEEdge.hxx>
//#include <NXOpen/CAE_CAEFace.hxx>
//#include <NXOpen/CAE_CaePart.hxx>
//#include <NXOpen/CAE_CAESet.hxx>
//#include <NXOpen/CAE_CAEVertex.hxx>
//#include <NXOpen/CAE_FEElement.hxx>
//#include <NXOpen/CAE_FEElementSet.hxx>
//#include <NXOpen/CAE_FEElementSetCollection.hxx>
//#include <NXOpen/CAE_FEModel.hxx>
//#include <NXOpen/CAE_FemPart.hxx>
//#include <NXOpen/CAE_FemSynchronizeOptions.hxx>
//#include <NXOpen/CAE_FENode.hxx>
//#include <NXOpen/CAE_FENodeSet.hxx>
//#include <NXOpen/CAE_FENodeSetCollection.hxx>
//#include <NXOpen/CAE_MeshPoint.hxx>
//#include <NXOpen/CAE_PropertyTable.hxx>
//#include <NXOpen/CAE_SetManager.hxx>
//#include <NXOpen/CAE_SetObject.hxx>
//#include <NXOpen/CAE_SetTargetObject.hxx>
//#include <NXOpen/CAE_SimBC.hxx>
//#include <NXOpen/CAE_SimBCBuilder.hxx>
//#include <NXOpen/CAE_SimBCDisplay.hxx>
//#include <NXOpen/CAE_SimConstraint.hxx>
//#include <NXOpen/CAE_SimConstraintCollection.hxx>
//#include <NXOpen/CAE_SimGroupContainer.hxx>
//#include <NXOpen/CAE_SimLoad.hxx>
//#include <NXOpen/CAE_SimLoadCollection.hxx>
//#include <NXOpen/CAE_SimPart.hxx>
//#include <NXOpen/CAE_SimResolveGroup.hxx>
//#include <NXOpen/CAE_SimResolveObject.hxx>
//#include <NXOpen/CAE_SimSimulation.hxx>
//#include <NXOpen/CAE_SimSimulationObject.hxx>
//#include <NXOpen/CAE_SimSimulationObjectCollection.hxx>
//#include <NXOpen/CAE_SimSolution.hxx>
//#include <NXOpen/CAE_SimSolutionStep.hxx>
//#include <NXOpen/CAE_XYFunctionDataTypes.hxx>
//#include <NXOpen/CAM_CAMObject.hxx>
//#include <NXOpen/CAM_CAMSession.hxx>
//#include <NXOpen/CAM_CAMSetup.hxx>
//#include <NXOpen/CAM_NCGroup.hxx>
//#include <NXOpen/CAM_NCGroupCollection.hxx>
//#include <NXOpen/CAM_Operation.hxx>
//#include <NXOpen/CAM_OperationCollection.hxx>
//#include <NXOpen/CartesianCoordinateSystem.hxx>
#include <NXOpen/ColorManager.hxx>
//#include <NXOpen/Conic.hxx>
//#include <NXOpen/CoordinateSystem.hxx>
//#include <NXOpen/CoordinateSystemCollection.hxx>
//#include <NXOpen/Curve.hxx>
//#include <NXOpen/CurveCollection.hxx>
//#include <NXOpen/CurveDumbRule.hxx>
//#include <NXOpen/CurveFeatureChainRule.hxx>
//#include <NXOpen/CurveFeatureRule.hxx>
//#include <NXOpen/CurveFeatureTangentRule.hxx>
//#include <NXOpen/CustomSymbols.hxx>
//#include <NXOpen/CutView.hxx>
//#include <NXOpen/CutViewCollection.hxx>
//#include <NXOpen/CylindricalCoordinateSystem.hxx>
//#include <NXOpen/DatumAxis.hxx>
//#include <NXOpen/DatumAxisConstraint.hxx>
//#include <NXOpen/DatumCollection.hxx>
//#include <NXOpen/DatumConstraint.hxx>
//#include <NXOpen/DatumPlane.hxx>
//#include <NXOpen/Die.hxx>
//#include <NXOpen/Die_CastReliefParentBuilder.hxx>
//#include <NXOpen/Die_ConnectProfileParentBuilder.hxx>
//#include <NXOpen/Die_DeckParentBuilder.hxx>
//#include <NXOpen/Die_DieCollection.hxx>
//#include <NXOpen/Die_DrawDiePunchBuilder.hxx>
//#include <NXOpen/Die_DrawDiePunchSectionBuilder.hxx>
//#include <NXOpen/Die_FillBuilder.hxx>
//#include <NXOpen/Die_FlangeSteelRibChildBuilder.hxx>
//#include <NXOpen/Die_FlangeSteelRibParentBuilder.hxx>
//#include <NXOpen/Die_FlangeTaskBuilder.hxx>
//#include <NXOpen/Die_FormTaskBuilder.hxx>
//#include <NXOpen/Die_HandlingCoreChildBuilder.hxx>
//#include <NXOpen/Die_HandlingCoreParentBuilder.hxx>
//#include <NXOpen/Die_HoleChildBuilder.hxx>
//#include <NXOpen/Die_HoleParentBuilder.hxx>
//#include <NXOpen/Die_KeywayChildBuilder.hxx>
//#include <NXOpen/Die_KeywayParentBuilder.hxx>
//#include <NXOpen/Die_LineupBuilder.hxx>
//#include <NXOpen/Die_OutputCurvesBuilder.hxx>
//#include <NXOpen/Die_PadChildBuilder.hxx>
//#include <NXOpen/Die_PadParentBuilder.hxx>
//#include <NXOpen/Die_PierceHoleChildBuilder.hxx>
//#include <NXOpen/Die_PierceHoleParentBuilder.hxx>
//#include <NXOpen/Die_PierceTaskBuilder.hxx>
//#include <NXOpen/Die_PointChildBuilder.hxx>
//#include <NXOpen/Die_PointParentBuilder.hxx>
//#include <NXOpen/Die_PressureSystemChildBuilder.hxx>
//#include <NXOpen/Die_PressureSystemParentBuilder.hxx>
//#include <NXOpen/Die_RibChildBuilder.hxx>
//#include <NXOpen/Die_RibParentBuilder.hxx>
//#include <NXOpen/Die_RotorBuilder.hxx>
//#include <NXOpen/Die_RotorSectionBuilder.hxx>
//#include <NXOpen/Die_SteelInsertBuilder.hxx>
//#include <NXOpen/Die_SteelInsertSectionBuilder.hxx>
//#include <NXOpen/Die_SteelInsertSegmentChildBuilder.hxx>
//#include <NXOpen/Die_SteelInsertSegmentParentBuilder.hxx>
//#include <NXOpen/Die_ThroatChildBuilder.hxx>
//#include <NXOpen/Die_ThroatParentBuilder.hxx>
//#include <NXOpen/Die_Tip.hxx>
//#include <NXOpen/Die_TrimTaskBuilder.hxx>
//#include <NXOpen/Die_WearPlateLocChildBuilder.hxx>
//#include <NXOpen/Die_WearPlateLocParentBuilder.hxx>
#include <NXOpen/Dimensions.hxx>
//#include <NXOpen/Direction.hxx>
//#include <NXOpen/DirectionCollection.hxx>
//#include <NXOpen/DisplayableObject.hxx>
//#include <NXOpen/DisplayManager.hxx>
//#include <NXOpen/DisplayModification.hxx>
#include <NXOpen/DraftingManager.hxx>
//#include <NXOpen/DraftPointDataCollection.hxx>
#include <NXOpen/Drawings_BaseView.hxx>
#include <NXOpen/Drawings_DetailView.hxx>
#include <NXOpen/Drawings_DetailViewBuilder.hxx>
//#include <NXOpen/Drawings_DraftingView.hxx>
#include <NXOpen/Drawings_DraftingViewCollection.hxx>
//#include <NXOpen/Drawings_DrawingSheet.hxx>
#include <NXOpen/Drawings_DrawingSheetCollection.hxx>
#include <NXOpen/Drawings_GeneralViewStyle.hxx>
#include <NXOpen/Drawings_SectionLine.hxx>
#include <NXOpen/Drawings_SectionLineCollection.hxx>
#include <NXOpen/Drawings_ViewStyle.hxx>
//#include <NXOpen/Edge.hxx>
//#include <NXOpen/EdgeBodyRule.hxx>
//#include <NXOpen/EdgeBoundaryRule.hxx>
//#include <NXOpen/EdgeChainRule.hxx>
//#include <NXOpen/EdgeDumbRule.hxx>
//#include <NXOpen/EdgeFaceRule.hxx>
//#include <NXOpen/EdgeFeatureRule.hxx>
//#include <NXOpen/EdgeIntersectRule.hxx>
//#include <NXOpen/EdgeMultipleSeedTangentRule.hxx>
//#include <NXOpen/EdgeSheetBoundaryRule.hxx>
//#include <NXOpen/EdgeTangentRule.hxx>
//#include <NXOpen/EdgeVertexRule.hxx>
//#include <NXOpen/EdgeVertexTangentRule.hxx>
//#include <NXOpen/Ellipse.hxx>
//#include <NXOpen/EllipseCollection.hxx>
//#include <NXOpen/EngineeringFunction.hxx>
//#include <NXOpen/ErrorInfo.hxx>
//#include <NXOpen/ErrorList.hxx>
//#include <NXOpen/Expression.hxx>
//#include <NXOpen/ExpressionCollection.hxx>
//#include <NXOpen/ExpressionSet.hxx>
//#include <NXOpen/Face.hxx>
//#include <NXOpen/FaceAdjacentRule.hxx>
//#include <NXOpen/FaceBodyRule.hxx>
//#include <NXOpen/FaceDumbRule.hxx>
//#include <NXOpen/FaceFeatureRule.hxx>
//#include <NXOpen/FaceRegionRule.hxx>
//#include <NXOpen/FaceTangentRule.hxx>
//#include <NXOpen/Features_AOCS.hxx>
//#include <NXOpen/Features_AOCSBuilder.hxx>
//#include <NXOpen/Features_Block.hxx>
//#include <NXOpen/Features_BlockFeatureBuilder.hxx>
//#include <NXOpen/Features_BodyFeature.hxx>
//#include <NXOpen/Features_BooleanBuilder.hxx>
//#include <NXOpen/Features_BooleanFeature.hxx>
//#include <NXOpen/Features_ChamferBuilder.hxx>
//#include <NXOpen/Features_CurveLength.hxx>
//#include <NXOpen/Features_CurveLengthBuilder.hxx>
//#include <NXOpen/Features_DatumAxisBuilder.hxx>
//#include <NXOpen/Features_DatumAxisFeature.hxx>
//#include <NXOpen/Features_DatumBuilder.hxx>
//#include <NXOpen/Features_DatumCsys.hxx>
//#include <NXOpen/Features_DatumCsysBuilder.hxx>
//#include <NXOpen/Features_DatumFeature.hxx>
//#include <NXOpen/Features_DatumPlaneBuilder.hxx>
//#include <NXOpen/Features_DatumPlaneFeature.hxx>
//#include <NXOpen/Features_DividefaceBuilder.hxx>
//#include <NXOpen/Features_DraftBuilder.hxx>
//#include <NXOpen/Features_DrawDiePunch.hxx>
//#include <NXOpen/Features_EdgeBlendBuilder.hxx>
//#include <NXOpen/Features_Emboss.hxx>
//#include <NXOpen/Features_EmbossBuilder.hxx>
//#include <NXOpen/Features_EmbossJoggle.hxx>
//#include <NXOpen/Features_EmbossLimit.hxx>
//#include <NXOpen/Features_EmbossProjection.hxx>
//#include <NXOpen/Features_EmbossRegion.hxx>
//#include <NXOpen/Features_EmbossSidewall.hxx>
//#include <NXOpen/Features_EmbossTaper.hxx>
//#include <NXOpen/Features_EmbossTarget.hxx>
//#include <NXOpen/Features_Extrude.hxx>
//#include <NXOpen/Features_ExtrudeBuilder.hxx>
//#include <NXOpen/Features_ExtrudeFeatureBuilder.hxx>
//#include <NXOpen/Features_ExtrudeLimitData.hxx>
//#include <NXOpen/Features_ExtrudeOffsetData.hxx>
//#include <NXOpen/Features_ExtrudeTaperData.hxx>
//#include <NXOpen/Features_FaceBlend.hxx>
//#include <NXOpen/Features_FaceBlendBuilder.hxx>
//#include <NXOpen/Features_Feature.hxx>
//#include <NXOpen/Features_FeatureBuilder.hxx>
//#include <NXOpen/Features_FeatureCollection.hxx>
//#include <NXOpen/Features_Hole.hxx>
//#include <NXOpen/Features_HoleFeatureBuilder.hxx>
//#include <NXOpen/Features_Human.hxx>
//#include <NXOpen/Features_HumanBuilder.hxx>
//#include <NXOpen/Features_IBoolean.hxx>
//#include <NXOpen/Features_Intersect.hxx>
//#include <NXOpen/Features_MasterCutBuilder.hxx>
//#include <NXOpen/Features_MeshSurfaceBuilder.hxx>
//#include <NXOpen/Features_OffsetSurfaceBuilder.hxx>
//#include <NXOpen/Features_OvercrownBuilder.hxx>
//#include <NXOpen/Features_RasterImage.hxx>
//#include <NXOpen/Features_Revolve.hxx>
//#include <NXOpen/Features_RevolveBuilder.hxx>
//#include <NXOpen/Features_Rotor.hxx>
//#include <NXOpen/Features_RPO.hxx>
//#include <NXOpen/Features_RPOAssociativityType.hxx>
//#include <NXOpen/Features_RPOBuilder.hxx>
//#include <NXOpen/Features_RPODimension.hxx>
//#include <NXOpen/Features_Ruled.hxx>
//#include <NXOpen/Features_SheetMetal_AeroFlangeBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_AeroJoggleBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_AeroReformBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_AeroSheetmetalManager.hxx>
//#include <NXOpen/Features_SheetMetal_AeroUnformBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_BeadBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_BendOptions.hxx>
//#include <NXOpen/Features_SheetMetal_BreakCornerBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_ContourFlangeBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_ConvertToSheetmetalBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_DimpleBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_DrawnCutoutBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_EdgeRipBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_FlangeBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_FlatSolidBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_LoftedFlangeBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_LouverBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_MiterOptions.hxx>
//#include <NXOpen/Features_SheetMetal_NormalCutoutBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_SheetmetalManager.hxx>
//#include <NXOpen/Features_SheetMetal_TabBuilder.hxx>
//#include <NXOpen/Features_SheetMetal_ThreeBendCornerBuilder.hxx>
//#include <NXOpen/Features_Shell.hxx>
//#include <NXOpen/Features_ShellBuilder.hxx>
//#include <NXOpen/Features_SketchFeature.hxx>
//#include <NXOpen/Features_SketchOnPathBuilder.hxx>
//#include <NXOpen/Features_Subtract.hxx>
//#include <NXOpen/Features_ThroughCurveMesh.hxx>
//#include <NXOpen/Features_ThroughCurves.hxx>
//#include <NXOpen/Features_TrimBody.hxx>
//#include <NXOpen/Features_TrimBodyBuilder.hxx>
//#include <NXOpen/Features_Unite.hxx>
//#include <NXOpen/Features_Varsweep.hxx>
//#include <NXOpen/Features_VarsweepBuilder.hxx>
//#include <NXOpen/Fields_Field.hxx>
//#include <NXOpen/Fields_FieldDomain.hxx>
//#include <NXOpen/Fields_FieldDomainCollection.hxx>
//#include <NXOpen/Fields_FieldExpression.hxx>
//#include <NXOpen/Fields_FieldManager.hxx>
//#include <NXOpen/Fields_FieldVariable.hxx>
//#include <NXOpen/FileNew.hxx>
//#include <NXOpen/FollowFilletRule.hxx>
#include <NXOpen/FontCollection.hxx>
//#include <NXOpen/Gdts.hxx>
//#include <NXOpen/GenericMeasure.hxx>
//#include <NXOpen/GeometricUtilities_AngularLimits.hxx>
//#include <NXOpen/GeometricUtilities_BooleanOperation.hxx>
//#include <NXOpen/GeometricUtilities_CircularCrossSection.hxx>
//#include <NXOpen/GeometricUtilities_ConicCrossSection.hxx>
//#include <NXOpen/GeometricUtilities_CurveLengthData.hxx>
//#include <NXOpen/GeometricUtilities_DraftPointData.hxx>
//#include <NXOpen/GeometricUtilities_DraftVariableAngleData.hxx>
//#include <NXOpen/GeometricUtilities_Extend.hxx>
//#include <NXOpen/GeometricUtilities_FaceSetOffset.hxx>
//#include <NXOpen/GeometricUtilities_FaceSetOffsetCollection.hxx>
//#include <NXOpen/GeometricUtilities_FeatureOffset.hxx>
//#include <NXOpen/GeometricUtilities_FeatureOptions.hxx>
//#include <NXOpen/GeometricUtilities_IComponentBuilder.hxx>
//#include <NXOpen/GeometricUtilities_Limits.hxx>
//#include <NXOpen/GeometricUtilities_LinearLimits.hxx>
//#include <NXOpen/GeometricUtilities_ProjectionOptions.hxx>
//#include <NXOpen/GeometricUtilities_SimpleDraft.hxx>
//#include <NXOpen/HumanData.hxx>
//#include <NXOpen/HumanHandShapeData.hxx>
//#include <NXOpen/HumanReachZone.hxx>
//#include <NXOpen/Hyperbola.hxx>
//#include <NXOpen/HyperbolaCollection.hxx>
//#include <NXOpen/IBaseCurve.hxx>
//#include <NXOpen/IBody.hxx>
//#include <NXOpen/ICurve.hxx>
//#include <NXOpen/IFitTo.hxx>
//#include <NXOpen/ILocation.hxx>
#include <NXOpen/Information.hxx>
//#include <NXOpen/INXObject.hxx>
//#include <NXOpen/IOMName.hxx>
//#include <NXOpen/IOrientation.hxx>
//#include <NXOpen/IParameterizedSurface.hxx>
//#include <NXOpen/IPlane.hxx>
//#include <NXOpen/IProfile.hxx>
//#include <NXOpen/IReferenceAxis.hxx>
//#include <NXOpen/ISketchHelpedConstraint.hxx>
//#include <NXOpen/ISurface.hxx>
//#include <NXOpen/JamSession.hxx>
//#include <NXOpen/JamTest.hxx>
//#include <NXOpen/JamTestNamespace_Subobject.hxx>
//#include <NXOpen/JamTestNamespace_Subspace_Tagged2.hxx>
//#include <NXOpen/JamTestNamespace_Subspace_Tagged2b.hxx>
//#include <NXOpen/JamTestNamespace_Subspace_TransientObj.hxx>
//#include <NXOpen/JamTestNamespace_Subspace_TransientObjB.hxx>
//#include <NXOpen/JamTestNamespace_Tagged.hxx>
//#include <NXOpen/JamTestPointer.hxx>
//#include <NXOpen/JamTestPointerSubclass.hxx>
//#include <NXOpen/Layer.hxx>
//#include <NXOpen/Layer_Category.hxx>
//#include <NXOpen/Layer_CategoryCollection.hxx>
//#include <NXOpen/Layer_LayerManager.hxx>
//#include <NXOpen/Layer_StateCollection.hxx>
//#include <NXOpen/Layout.hxx>
//#include <NXOpen/LayoutCollection.hxx>
//#include <NXOpen/LayoutDefinition.hxx>
//#include <NXOpen/libnxopencpp_exports.hxx>
//#include <NXOpen/libnxopenjamtestcpp_exports.hxx>
//#include <NXOpen/libnxopenuicpp_exports.hxx>
//#include <NXOpen/LicenseManager.hxx>
//#include <NXOpen/Light.hxx>
//#include <NXOpen/LightCollection.hxx>
//#include <NXOpen/Line.hxx>
//#include <NXOpen/LineCollection.hxx>
//#include <NXOpen/LineWelds.hxx>
//#include <NXOpen/ListingWindow.hxx>
//#include <NXOpen/LoadOptions.hxx>
//#include <NXOpen/LogFile.hxx>
//#include <NXOpen/MathUtils.hxx>
//#include <NXOpen/Measure.hxx>
//#include <NXOpen/MeasureAngle.hxx>
//#include <NXOpen/MeasureBodies.hxx>
//#include <NXOpen/MeasureDistance.hxx>
//#include <NXOpen/MeasureFaces.hxx>
//#include <NXOpen/MeasureLength.hxx>
//#include <NXOpen/MeasureManager.hxx>
//#include <NXOpen/Measurement.hxx>
#include <NXOpen/MenuBar_MenuBarManager.hxx>
//#include <NXOpen/MeshParameterData.hxx>
//#include <NXOpen/MeshProfileString.hxx>
#include <NXOpen/ModelingView.hxx>
#include <NXOpen/ModelingViewCollection.hxx>
//#include <NXOpen/ModelingViewHighQualityImage.hxx>
//#include <NXOpen/Motion_Link.hxx>
//#include <NXOpen/Motion_Marker.hxx>
//#include <NXOpen/Motion_MarkerCollection.hxx>
//#include <NXOpen/Motion_Packaging.hxx>
//#include <NXOpen/Motion_PackagingBuilder.hxx>
//#include <NXOpen/Motion_PackagingCollection.hxx>
//#include <NXOpen/Motion_PackagingInterference.hxx>
//#include <NXOpen/Motion_PackagingInterferenceBuilder.hxx>
//#include <NXOpen/Motion_PackagingMeasure.hxx>
//#include <NXOpen/Motion_PackagingMeasureBuilder.hxx>
//#include <NXOpen/Motion_PackagingTrace.hxx>
//#include <NXOpen/Motion_PackagingTraceBuilder.hxx>
#include <NXOpen/NXException.hxx>
//#include <NXOpen/NXMatrix.hxx>
//#include <NXOpen/NXMatrixCollection.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/NXObjectManager.hxx>
//#include <NXOpen/NXString.hxx>
//#include <NXOpen/ObjectList.hxx>
//#include <NXOpen/Offset.hxx>
//#include <NXOpen/OffsetCollection.hxx>
//#include <NXOpen/OMAttribute.hxx>
//#include <NXOpen/OMClass.hxx>
//#include <NXOpen/OMSchema.hxx>
//#include <NXOpen/Options_ChangeList.hxx>
//#include <NXOpen/Options_OptionsManager.hxx>
//#include <NXOpen/Parabola.hxx>
//#include <NXOpen/ParabolaCollection.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCleanup.hxx>
//#include <NXOpen/PartCloseResponses.hxx>
#include <NXOpen/PartCollection.hxx>
//#include <NXOpen/PartLoadStatus.hxx>
//#include <NXOpen/PartReopenReport.hxx>
//#include <NXOpen/PartReopenStatus.hxx>
//#include <NXOpen/PartSaveOptions.hxx>
//#include <NXOpen/PartSaveStatus.hxx>
//#include <NXOpen/PDM_AlternateIdManager.hxx>
//#include <NXOpen/PDM_DatabaseAttributeManager.hxx>
//#include <NXOpen/PDM_PartBuilder.hxx>
//#include <NXOpen/PDM_PartFromPartBuilder.hxx>
//#include <NXOpen/PDM_PartFromTemplateBuilder.hxx>
//#include <NXOpen/PDM_PartManager.hxx>
//#include <NXOpen/PDM_PdmPart.hxx>
//#include <NXOpen/PDM_PendingComponentsManager.hxx>
//#include <NXOpen/PDM_PersistentSettings.hxx>
#include <NXOpen/PDM_PdmSearch.hxx>
#include <NXOpen/PDM_PdmSearchManager.hxx>
#include <NXOpen/PDM_SearchResult.hxx>
//#include <NXOpen/PDM_SessionSettings.hxx>
//#include <NXOpen/Plane.hxx>
//#include <NXOpen/PlaneCollection.hxx>
//#include <NXOpen/PlaneTypes.hxx>
//#include <NXOpen/Point.hxx>
//#include <NXOpen/PointCollection.hxx>
//#include <NXOpen/PositioningDimension.hxx>
//#include <NXOpen/Positioning_ComponentPositioner.hxx>
//#include <NXOpen/Positioning_Constraint.hxx>
//#include <NXOpen/Positioning_ConstraintReference.hxx>
//#include <NXOpen/Positioning_Network.hxx>
//#include <NXOpen/Positioning_Positioner.hxx>
#include <NXOpen/Preferences_AnnotationPreferences.hxx>
#include <NXOpen/Preferences_BaseViewPreferences.hxx>
#include <NXOpen/Preferences_DetailViewPreferences.hxx>
#include <NXOpen/Preferences_DraftingPreferenceManager.hxx>
#include <NXOpen/Preferences_FlatPatternViewPreferences.hxx>
#include <NXOpen/Preferences_GeneralViewPreferences.hxx>
#include <NXOpen/Preferences_HiddenLinesViewPreferences.hxx>
#include <NXOpen/Preferences_InheritPmiPreferences.hxx>
#include <NXOpen/Preferences_LoadDraftingStandardBuilder.hxx>
//#include <NXOpen/Preferences_ObjectPreferences.hxx>
//#include <NXOpen/Preferences_PartAeroSheetmetal.hxx>
#include <NXOpen/Preferences_PartDrafting.hxx>
//#include <NXOpen/Preferences_PartFlexiblePrintedCircuitDesign.hxx>
//#include <NXOpen/Preferences_PartModeling.hxx>
//#include <NXOpen/Preferences_PartObject.hxx>
#include <NXOpen/Preferences_PartPreferences.hxx>
//#include <NXOpen/Preferences_PartSheetmetal.hxx>
//#include <NXOpen/Preferences_PartSketch.hxx>
//#include <NXOpen/Preferences_PartUserInterface.hxx>
#include <NXOpen/Preferences_PartVisualizationColorSetting.hxx>
#include <NXOpen/Preferences_PartVisualizationLine.hxx>
//#include <NXOpen/Preferences_PartVisualizationNamesBorders.hxx>
//#include <NXOpen/Preferences_PartVisualizationShade.hxx>
//#include <NXOpen/Preferences_PartVisualizationVisual.hxx>
#include <NXOpen/Preferences_ProjectedViewPreferences.hxx>
//#include <NXOpen/Preferences_RoutingApplicationView.hxx>
//#include <NXOpen/Preferences_RoutingCharacteristics.hxx>
//#include <NXOpen/Preferences_RoutingElectrical.hxx>
//#include <NXOpen/Preferences_RoutingLogical.hxx>
//#include <NXOpen/Preferences_RoutingMechanical.hxx>
//#include <NXOpen/Preferences_RoutingPart.hxx>
//#include <NXOpen/Preferences_RoutingPartLibrary.hxx>
//#include <NXOpen/Preferences_RoutingPath.hxx>
//#include <NXOpen/Preferences_RoutingStock.hxx>
//#include <NXOpen/Preferences_RulePreferences.hxx>
#include <NXOpen/Preferences_SectionViewPreferences.hxx>
#include <NXOpen/Preferences_ShadingViewPreferences.hxx>
#include <NXOpen/Preferences_ShipbuildingLinesViewPreferences.hxx>
#include <NXOpen/Preferences_SmoothEdgesViewPreferences.hxx>
//#include <NXOpen/Preferences_SessionAssemblies.hxx>
//#include <NXOpen/Preferences_SessionDrafting.hxx>
//#include <NXOpen/Preferences_SessionModeling.hxx>
//#include <NXOpen/Preferences_SessionNXGateway.hxx>
//#include <NXOpen/Preferences_SessionPdm.hxx>
//#include <NXOpen/Preferences_SessionPmi.hxx>
//#include <NXOpen/Preferences_SessionPreferences.hxx>
//#include <NXOpen/Preferences_SessionSketch.hxx>
//#include <NXOpen/Preferences_SessionUserInterface.hxx>
//#include <NXOpen/Preferences_SessionUserInterfaceUI.hxx>
//#include <NXOpen/Preferences_SessionVisualizationColorSetting.hxx>
#include <NXOpen/Preferences_SessionVisualizationHighEndRendering.hxx>
//#include <NXOpen/Preferences_SessionVisualizationHighQualityImage.hxx>
//#include <NXOpen/Preferences_SessionVisualizationScreen.hxx>
//#include <NXOpen/Preferences_SessionVisualizationShade.hxx>
//#include <NXOpen/Preferences_SessionVisualizationVisual.hxx>
//#include <NXOpen/Preferences_SessionWorkPlane.hxx>
//#include <NXOpen/Preferences_SketchPreferences.hxx>
#include <NXOpen/Preferences_ThreadsViewPreferences.hxx>
#include <NXOpen/Preferences_TraceLinesViewPreferences.hxx>
#include <NXOpen/Preferences_ViewPreferences.hxx>
//#include <NXOpen/Preferences_ViewVisualizationSpecialEffects.hxx>
#include <NXOpen/Preferences_ViewVisualizationVisual.hxx>
#include <NXOpen/Preferences_VirtualIntersectionsViewPreferences.hxx>
#include <NXOpen/Preferences_VisibleLinesViewPreferences.hxx>
#include <NXOpen/Preferences_VisualizationLine.hxx>
//#include <NXOpen/Preferences_WorkPlane.hxx>
//#include <NXOpen/RemoteUtilities.hxx>
//#include <NXOpen/Routing_Anchor.hxx>
//#include <NXOpen/Routing_AnchorCollection.hxx>
//#include <NXOpen/Routing_ArcSegment.hxx>
//#include <NXOpen/Routing_ArcSegmentCollection.hxx>
//#include <NXOpen/Routing_AssemblyDefinition.hxx>
//#include <NXOpen/Routing_BendCorner.hxx>
//#include <NXOpen/Routing_BendCornerCollection.hxx>
//#include <NXOpen/Routing_BuiltInPath.hxx>
//#include <NXOpen/Routing_BuiltInPathCollection.hxx>
//#include <NXOpen/Routing_CharacteristicList.hxx>
//#include <NXOpen/Routing_ConnectivityDefinition.hxx>
//#include <NXOpen/Routing_ControlPoint.hxx>
//#include <NXOpen/Routing_ControlPointCollection.hxx>
//#include <NXOpen/Routing_CopeCorner.hxx>
//#include <NXOpen/Routing_CopeCornerCollection.hxx>
//#include <NXOpen/Routing_Corner.hxx>
//#include <NXOpen/Routing_CornerCollection.hxx>
//#include <NXOpen/Routing_CrossSection.hxx>
//#include <NXOpen/Routing_CrossSectionCollection.hxx>
//#include <NXOpen/Routing_DesignRule.hxx>
//#include <NXOpen/Routing_DesignRuleCollection.hxx>
//#include <NXOpen/Routing_DesignRuleManager.hxx>
//#include <NXOpen/Routing_DesignRuleOverride.hxx>
//#include <NXOpen/Routing_DesignRuleViolation.hxx>
//#include <NXOpen/Routing_DesignRuleViolationCollection.hxx>
//#include <NXOpen/Routing_DeviceRelationship.hxx>
//#include <NXOpen/Routing_DiscontinuityCorner.hxx>
//#include <NXOpen/Routing_DiscontinuityCornerCollection.hxx>
//#include <NXOpen/Routing_Electrical_CableConnection.hxx>
//#include <NXOpen/Routing_Electrical_CableConnectionCollection.hxx>
//#include <NXOpen/Routing_Electrical_CableDefinition.hxx>
//#include <NXOpen/Routing_Electrical_CableDevice.hxx>
//#include <NXOpen/Routing_Electrical_CableStockDefinition.hxx>
//#include <NXOpen/Routing_Electrical_Connection.hxx>
//#include <NXOpen/Routing_Electrical_ConnectionCollection.hxx>
//#include <NXOpen/Routing_Electrical_ConnectorDevice.hxx>
//#include <NXOpen/Routing_Electrical_ConnectorDeviceCollection.hxx>
//#include <NXOpen/Routing_Electrical_ElectricalDeviceRelationship.hxx>
//#include <NXOpen/Routing_Electrical_ElectricalDeviceRelationshipCollection.hxx>
//#include <NXOpen/Routing_Electrical_ElectricalPartDefinitionShadow.hxx>
//#include <NXOpen/Routing_Electrical_ElectricalStockDefinition.hxx>
//#include <NXOpen/Routing_Electrical_ElectricalStockDevice.hxx>
//#include <NXOpen/Routing_Electrical_ElectricalStockDeviceCollection.hxx>
//#include <NXOpen/Routing_Electrical_HarnessDefinition.hxx>
//#include <NXOpen/Routing_Electrical_HarnessDevice.hxx>
//#include <NXOpen/Routing_Electrical_HarnessDeviceCollection.hxx>
//#include <NXOpen/Routing_Electrical_JumperConnection.hxx>
//#include <NXOpen/Routing_Electrical_JumperConnectionCollection.hxx>
//#include <NXOpen/Routing_Electrical_NonPathConnection.hxx>
//#include <NXOpen/Routing_Electrical_NonPathConnectionCollection.hxx>
//#include <NXOpen/Routing_Electrical_PathConnection.hxx>
//#include <NXOpen/Routing_Electrical_PathConnectionCollection.hxx>
//#include <NXOpen/Routing_Electrical_ShieldDefinition.hxx>
//#include <NXOpen/Routing_Electrical_ShieldDevice.hxx>
//#include <NXOpen/Routing_Electrical_ShieldStockDefinition.hxx>
//#include <NXOpen/Routing_Electrical_WireDevice.hxx>
//#include <NXOpen/Routing_ExtractPort.hxx>
//#include <NXOpen/Routing_Filler.hxx>
//#include <NXOpen/Routing_FillerCollection.hxx>
//#include <NXOpen/Routing_FittingPort.hxx>
//#include <NXOpen/Routing_FittingPortCollection.hxx>
//#include <NXOpen/Routing_FixturePort.hxx>
//#include <NXOpen/Routing_FixturePortCollection.hxx>
//#include <NXOpen/Routing_FormboardFrame.hxx>
//#include <NXOpen/Routing_FormboardFrameCollection.hxx>
//#include <NXOpen/Routing_IAxisPort.hxx>
//#include <NXOpen/Routing_ICharacteristic.hxx>
//#include <NXOpen/Routing_InterfaceTerminalBase.hxx>
//#include <NXOpen/Routing_InterfaceTerminalRelationshipBase.hxx>
//#include <NXOpen/Routing_InterfaceTerminalRelationshipCollection.hxx>
//#include <NXOpen/Routing_InterfaceTerminalRelationshipShadow.hxx>
//#include <NXOpen/Routing_InterfaceTerminalShadow.hxx>
//#include <NXOpen/Routing_IPath.hxx>
//#include <NXOpen/Routing_IRoutePosition.hxx>
//#include <NXOpen/Routing_ISegment.hxx>
//#include <NXOpen/Routing_ItemDefinition.hxx>
//#include <NXOpen/Routing_LineSegment.hxx>
//#include <NXOpen/Routing_LineSegmentCollection.hxx>
//#include <NXOpen/Routing_LogicalConnection.hxx>
//#include <NXOpen/Routing_LogicalTerminal.hxx>
//#include <NXOpen/Routing_MiterCorner.hxx>
//#include <NXOpen/Routing_MiterCornerCollection.hxx>
//#include <NXOpen/Routing_MultiPort.hxx>
//#include <NXOpen/Routing_MultiPortCollection.hxx>
//#include <NXOpen/Routing_ObjectRelationship.hxx>
//#include <NXOpen/Routing_OffsetPath.hxx>
//#include <NXOpen/Routing_OffsetPathCollection.hxx>
//#include <NXOpen/Routing_OverstockApplication.hxx>
//#include <NXOpen/Routing_OverstockApplicationCollection.hxx>
//#include <NXOpen/Routing_OverstockDevice.hxx>
//#include <NXOpen/Routing_PartDefinitionBase.hxx>
//#include <NXOpen/Routing_PartDefinitionShadow.hxx>
//#include <NXOpen/Routing_Port.hxx>
//#include <NXOpen/Routing_PortCollection.hxx>
//#include <NXOpen/Routing_PortConnection.hxx>
//#include <NXOpen/Routing_PortConnectionCollection.hxx>
//#include <NXOpen/Routing_RootObject.hxx>
//#include <NXOpen/Routing_RouteLogicalAssociation.hxx>
//#include <NXOpen/Routing_RouteLogicalAssociationCollection.hxx>
//#include <NXOpen/Routing_RouteManager.hxx>
//#include <NXOpen/Routing_RouteObject.hxx>
//#include <NXOpen/Routing_RoutePartDescriptor.hxx>
//#include <NXOpen/Routing_RoutePartDescriptorCollection.hxx>
//#include <NXOpen/Routing_RoutingSystem.hxx>
//#include <NXOpen/Routing_RoutingSystemCollection.hxx>
//#include <NXOpen/Routing_Run.hxx>
//#include <NXOpen/Routing_RunCollection.hxx>
//#include <NXOpen/Routing_SBendCorner.hxx>
//#include <NXOpen/Routing_SBendCornerCollection.hxx>
//#include <NXOpen/Routing_SegmentManager.hxx>
//#include <NXOpen/Routing_SingleDevice.hxx>
//#include <NXOpen/Routing_SplineSegment.hxx>
//#include <NXOpen/Routing_SplineSegmentCollection.hxx>
//#include <NXOpen/Routing_Stock.hxx>
//#include <NXOpen/Routing_StockCollection.hxx>
//#include <NXOpen/Routing_StockData.hxx>
//#include <NXOpen/Routing_StockDataCollection.hxx>
//#include <NXOpen/Routing_StockDefinition.hxx>
//#include <NXOpen/Routing_StockDevice.hxx>
//#include <NXOpen/Routing_StockPort.hxx>
//#include <NXOpen/Routing_TerminalPort.hxx>
//#include <NXOpen/Routing_TerminalPortCollection.hxx>
//#include <NXOpen/Routing_Wire.hxx>
//#include <NXOpen/Routing_WireCollection.hxx>
//#include <NXOpen/RuleManager.hxx>
//#include <NXOpen/SaveOptions.hxx>
//#include <NXOpen/Scalar.hxx>
//#include <NXOpen/ScalarCollection.hxx>
//#include <NXOpen/ScCollector.hxx>
//#include <NXOpen/ScCollectorCollection.hxx>
//#include <NXOpen/ScRuleFactory.hxx>
//#include <NXOpen/Section.hxx>
//#include <NXOpen/SectionCollection.hxx>
//#include <NXOpen/SectionData.hxx>
//#include <NXOpen/SectionElementData.hxx>
//#include <NXOpen/Selection.hxx>
//#include <NXOpen/SelectionIntentRule.hxx>
#include <NXOpen/Session.hxx>
//#include <NXOpen/SheetmetalFeatureProperty.hxx>
//#include <NXOpen/SingleMeasure.hxx>
//#include <NXOpen/Sketch.hxx>
//#include <NXOpen/SketchCollection.hxx>
//#include <NXOpen/SketchConstraint.hxx>
//#include <NXOpen/SketchDimensionalConstraint.hxx>
//#include <NXOpen/SketchEvaluator.hxx>
//#include <NXOpen/SketchEvaluatorCollection.hxx>
//#include <NXOpen/SketchGeometricConstraint.hxx>
//#include <NXOpen/SketchHelpedDimensionalConstraint.hxx>
//#include <NXOpen/SketchHelpedGeometricConstraint.hxx>
//#include <NXOpen/SketchTangentConstraint.hxx>
//#include <NXOpen/SmartObject.hxx>
//#include <NXOpen/SphericalCoordinateSystem.hxx>
//#include <NXOpen/Spline.hxx>
//#include <NXOpen/SurfaceRebuildData.hxx>
//#include <NXOpen/SymbolFont.hxx>
#include <NXOpen/TaggedObject.hxx>
//#include <NXOpen/TaggedObjectCollection.hxx>
//#include <NXOpen/Traceline.hxx>
//#include <NXOpen/TracelineCollection.hxx>
//#include <NXOpen/TransientObject.hxx>
//#include <NXOpen/type.hxx>
//#include <NXOpen/ugmath.hxx>
#include <NXOpen/UI.hxx>
//#include <NXOpen/Unit.hxx>
//#include <NXOpen/UnitCollection.hxx>
//#include <NXOpen/Update.hxx>
//#include <NXOpen/Validation.hxx>
//#include <NXOpen/ValidationCollection.hxx>
#include <NXOpen/View.hxx>
//#include <NXOpen/ViewCollection.hxx>
//#include <NXOpen/WCS.hxx>
//#include <NXOpen/Xform.hxx>
//#include <NXOpen/XformCollection.hxx>

using namespace NXOpen;

extern "C" DllExport void UG_debug(const char *fmt, ...);
extern "C" DllExport void UG_alert(const char *fmt, ...);
void UG_write_listing_window(char const *text);
void set_DEBUG(const int &val);
int is_DEBUG();

int list_Tags(void);
bool componentIsReference(Assemblies::Component *comp);

int get_Objects(tag_t part, int uf_object_type, int *num_objects, tag_t **objects);
int get_Object_type(tag_t obj, int *type);
int get_Object_subtype(tag_t obj, int *subtype);

extern "C" DllExport int reportError(char *file, int line, char *call, int irc);

#define UF_CALL(X) (reportError(__FILE__, __LINE__, # X, (X)))