
/****************************************************************************************
*   Author:       Matthias Kreissig
*   Datum:        16.05.2019
*   Beschreibung: Sammlung aller NX-Include-Dateien für en_nx_manage_drawing_standards.h
***************************************************************************************/
#include <math.h>
#include <stdarg.h>
#include <stdio.h>
//#include <windows.h>
#include <stdlib.h>
#include <typeinfo>

#include <uf_drf_errors.h>
#include <uf_obj_types.h>
#include <uf_drf_types.h>
#include <NXOpen/UI.hxx>
#include <uf_view.h>

#include <uf.h>
#include <uf_defs.h>
#include <uf_drf.h>
#include <uf_kf.h>
#include <uf_draw_types.h>
#include <uf_view.h>
#include <uf_draw.h>
#include <uf_so.h>
#include <uf_obj.h>
#include <NXOpen/ugmath.hxx>

#include <NXOpen/BasePart.hxx>
//#include <NXOpen/Builder.hxx>
//#include <NXOpen/NXString.hxx>
//#include <NXOpen/Callback.hxx
//#include <NXOpen/CallbackTest.hxx
//#include <NXOpen/CallbackTestNamespace_Subspace_CallbackTransientObj.hxx
//#include <NXOpen/CallbackTestNamespace_Subspace_CallbackTransientObjB.hxx
//#include <NXOpen/CallbackTestPointer.hxx
//#include <NXOpen/CDF.hxx
//#include <NXOpen/CollaborativeContentManager.hxx
//#include <NXOpen/CollaborativeDesign.hxx
//#include <NXOpen/CollaborativeDesignCollection.hxx
#include <NXOpen/ColorDefinition.hxx>
#include <NXOpen/ColorManager.hxx>
#include <NXOpen/ColorRegionRule.hxx>
#include <NXOpen/ColorWidth.hxx>
//#include <NXOpen/CustomPopupMenu.hxx
//#include <NXOpen/CustomPopupMenuHandler.hxx
//#include <NXOpen/CustomPopupMenuItem.hxx
//#include <NXOpen/CustomSymbols.hxx
//#include <NXOpen/CustomWidth.hxx
//#include <NXOpen/CutView.hxx
//#include <NXOpen/CutViewCollection.hxx
//#include <NXOpen/DataContainer.hxx
//#include <NXOpen/DebugUI.hxx
#include <NXOpen/Annotations.hxx>
//#include <NXOpen/Annotations_AddTicBuilder.hxx
//#include <NXOpen/Annotations_AngularDimension.hxx
//#include <NXOpen/Annotations_AngularDimensionBuilder.hxx
//#include <NXOpen/Annotations_AngularTolerance.hxx
#include <NXOpen/Annotations_Annotation.hxx>
#include <NXOpen/Annotations_AnnotationManager.hxx>
//#include <NXOpen/Annotations_AnnotationPlacement.hxx
#include <NXOpen/Annotations_AppendedText.hxx>
#include <NXOpen/Annotations_AppendedTextBuilder.hxx>
#include <NXOpen/Annotations_AppendedTextEditorBuilder.hxx>
//#include <NXOpen/Annotations_ArbitraryAreaSeedBuilder.hxx
//#include <NXOpen/Annotations_ArbitraryAreaSeedBuilderList.hxx
//#include <NXOpen/Annotations_ArbitraryTarget.hxx
//#include <NXOpen/Annotations_ArbitraryTargetData.hxx
//#include <NXOpen/Annotations_ArcComponent.hxx
//#include <NXOpen/Annotations_ArcLengthDimension.hxx
//#include <NXOpen/Annotations_AreaTarget.hxx
//#include <NXOpen/Annotations_ArrowComponent.hxx
//#include <NXOpen/Annotations_AssociateDimensionBuilder.hxx
//#include <NXOpen/Annotations_AssociatedObject.hxx
//#include <NXOpen/Annotations_AssociatedObjectsBuilder.hxx
//#include <NXOpen/Annotations_AssociatedObjectsSetsBuilder.hxx
//#include <NXOpen/Annotations_AssociativeText.hxx
//#include <NXOpen/Annotations_Associativity.hxx
//#include <NXOpen/Annotations_AssociativityBuilder.hxx
//#include <NXOpen/Annotations_AutomaticCenterlineBuilder.hxx
#include <NXOpen/Annotations_BalloonNote.hxx>
#include <NXOpen/Annotations_BalloonNoteBuilder.hxx>
//#include <NXOpen/Annotations_BaseAngularDimension.hxx
//#include <NXOpen/Annotations_BaseAngularDimensionBuilder.hxx
//#include <NXOpen/Annotations_BaseArcLengthDimension.hxx
//#include <NXOpen/Annotations_BaseArrow.hxx
//#include <NXOpen/Annotations_BaseBoltCircleCenterline.hxx
//#include <NXOpen/Annotations_BaseBoltCircleCenterlineBuilder.hxx
//#include <NXOpen/Annotations_BaseCenterline3d.hxx
//#include <NXOpen/Annotations_BaseCenterline3dBuilder.hxx
//#include <NXOpen/Annotations_BaseCenterMark.hxx
//#include <NXOpen/Annotations_BaseCenterMarkBuilder.hxx
//#include <NXOpen/Annotations_BaseChamferDimension.hxx
//#include <NXOpen/Annotations_BaseChamferDimensionBuilder.hxx
//#include <NXOpen/Annotations_BaseConcentricCircleDimension.hxx
//#include <NXOpen/Annotations_BaseCurveLengthDimensionBuilder.hxx
//#include <NXOpen/Annotations_BaseCustomSymbol.hxx
//#include <NXOpen/Annotations_BaseCustomSymbolBuilder.hxx
//#include <NXOpen/Annotations_BaseCylindricalDimension.hxx
//#include <NXOpen/Annotations_BaseDatum.hxx
//#include <NXOpen/Annotations_BaseDatumTarget.hxx
//#include <NXOpen/Annotations_BaseDiameterDimension.hxx
//#include <NXOpen/Annotations_BaseFcf.hxx
//#include <NXOpen/Annotations_BaseFoldedRadiusDimension.hxx
//#include <NXOpen/Annotations_BaseFrameBar.hxx
//#include <NXOpen/Annotations_BaseFrameBarBuilder.hxx
//#include <NXOpen/Annotations_BaseHoleDimension.hxx
//#include <NXOpen/Annotations_BaseHorizontalDimension.hxx
//#include <NXOpen/Annotations_BaseLinearDimensionBuilder.hxx
//#include <NXOpen/Annotations_BaselineDimension.hxx
//#include <NXOpen/Annotations_BaseNote.hxx
//#include <NXOpen/Annotations_BaseOrdinateDimensionBuilder.hxx
//#include <NXOpen/Annotations_BaseParallelDimension.hxx
//#include <NXOpen/Annotations_BasePerpendicularDimension.hxx
//#include <NXOpen/Annotations_BaseRadialDimensionBuilder.hxx
//#include <NXOpen/Annotations_BaseRadiusDimension.hxx
//#include <NXOpen/Annotations_BaseRapidDimensionBuilder.hxx
//#include <NXOpen/Annotations_BaseSurfaceFinish.hxx
//#include <NXOpen/Annotations_BaseSurfaceFinishBuilder.hxx
//#include <NXOpen/Annotations_BaseSymbolBuilder.hxx
//#include <NXOpen/Annotations_BaseThicknessDimensionBuilder.hxx
//#include <NXOpen/Annotations_BaseTitleBlockBuilder.hxx
//#include <NXOpen/Annotations_BaseVerticalDimension.hxx
//#include <NXOpen/Annotations_BendTable.hxx
//#include <NXOpen/Annotations_BendTableBuilder.hxx
//#include <NXOpen/Annotations_BendTableCollection.hxx
//#include <NXOpen/Annotations_BendTableSettingsBuilder.hxx>
//#include <NXOpen/Annotations_BillOfMaterialBuilder.hxx
//#include <NXOpen/Annotations_BoltCircleCenterline.hxx
//#include <NXOpen/Annotations_BoltCircleCenterlineBuilder.hxx
//#include <NXOpen/Annotations_BoundaryBuilder.hxx
//#include <NXOpen/Annotations_BreakSettingsBuilder.hxx
//#include <NXOpen/Annotations_BusinessModifier.hxx
//#include <NXOpen/Annotations_BusinessModifierCollection.hxx
#include <NXOpen/Annotations_CalloutGroupBuilder.hxx>
#include <NXOpen/Annotations_Centerline.hxx>
//#include <NXOpen/Annotations_Centerline2d.hxx
//#include <NXOpen/Annotations_Centerline2dBuilder.hxx
#include <NXOpen/Annotations_Centerline2dSettingsBuilder.hxx>
//#include <NXOpen/Annotations_Centerline3d.hxx
//#include <NXOpen/Annotations_Centerline3dBuilder.hxx
//#include <NXOpen/Annotations_Centerline3dSettingsBuilder.hxx
#include <NXOpen/Annotations_CenterlineBuilder.hxx>
#include <NXOpen/Annotations_CenterlineCollection.hxx>
#include <NXOpen/Annotations_CenterlineSettingsBuilder.hxx>
//#include <NXOpen/Annotations_CenterMark.hxx
//#include <NXOpen/Annotations_CenterMarkBuilder.hxx
//#include <NXOpen/Annotations_CenterMarkSettingsBuilder.hxx
//#include <NXOpen/Annotations_ChainDimension.hxx
//#include <NXOpen/Annotations_ChamferDimension.hxx
//#include <NXOpen/Annotations_ChamferDimensionBuilder.hxx
#include <NXOpen/Annotations_ChamferDimensionPreferences.hxx>
//#include <NXOpen/Annotations_CircleCenterline.hxx
//#include <NXOpen/Annotations_CircleCenterlineBuilder.hxx
//#include <NXOpen/Annotations_CircleCenterlineSettingsBuilder.hxx
//#include <NXOpen/Annotations_CircularCenterline.hxx
//#include <NXOpen/Annotations_CircularCenterlineBuilder.hxx
//#include <NXOpen/Annotations_CircularTarget.hxx
//#include <NXOpen/Annotations_CircularTargetData.hxx
#include <NXOpen/Annotations_CommonWorkflowBuilder.hxx>
//#include <NXOpen/Annotations_CompanyProprietaryInformation.hxx
//#include <NXOpen/Annotations_CompanyProprietaryInformationBuilder.hxx
//#include <NXOpen/Annotations_ComponentData.hxx
//#include <NXOpen/Annotations_CompoundDatumReferenceBuilder.hxx
//#include <NXOpen/Annotations_ConcentricCircleDimension.hxx
//#include <NXOpen/Annotations_CoordinateNote.hxx
//#include <NXOpen/Annotations_CoordinateNoteBuilder.hxx
//#include <NXOpen/Annotations_CurveLengthDimensionBuilder.hxx
//#include <NXOpen/Annotations_CustomerValueBusinessModifier.hxx
//#include <NXOpen/Annotations_CustomerValueBusinessModifierBuilder.hxx
//#include <NXOpen/Annotations_CustomSymbol.hxx
//#include <NXOpen/Annotations_CustomSymbolCollection.hxx
//#include <NXOpen/Annotations_CustomSymbolData.hxx
//#include <NXOpen/Annotations_CustomSymbolLeaderBuilder.hxx
#include <NXOpen/Annotations_CustomSymbolTextData.hxx>
//#include <NXOpen/Annotations_CutSheetBuilder.hxx
//#include <NXOpen/Annotations_CuttingPlaneSymbol.hxx
//#include <NXOpen/Annotations_CuttingPlaneSymbolBuilder.hxx
//#include <NXOpen/Annotations_CylindricalDimension.hxx
//#include <NXOpen/Annotations_Datum.hxx
//#include <NXOpen/Annotations_DatumData.hxx
//#include <NXOpen/Annotations_DatumFeatureSymbolBuilder.hxx
//#include <NXOpen/Annotations_DatumReference.hxx
//#include <NXOpen/Annotations_DatumReferenceBuilder.hxx
//#include <NXOpen/Annotations_DatumReferenceBuilderList.hxx
//#include <NXOpen/Annotations_DatumTarget.hxx
//#include <NXOpen/Annotations_DatumTargetBuilder.hxx
//#include <NXOpen/Annotations_DatumTargetCollection.hxx
//#include <NXOpen/Annotations_DatumTargetData.hxx
//#include <NXOpen/Annotations_DefineTitleBlockBuilder.hxx
//#include <NXOpen/Annotations_DiameterDimension.hxx
//#include <NXOpen/Annotations_DiameterRadiusPreferences.hxx
//#include <NXOpen/Annotations_Dimension.hxx>
#include <NXOpen/Annotations_DimensionCollection.hxx>
//#include <NXOpen/Annotations_DimensionData.hxx
//#include <NXOpen/Annotations_DimensionMeasurementBuilder.hxx
#include <NXOpen/Annotations_DimensionPreferences.hxx>
//#include <NXOpen/Annotations_DimensionSet.hxx
//#include <NXOpen/Annotations_DimensionSetBuilder.hxx
//#include <NXOpen/Annotations_DimensionSetCollection.hxx
#include <NXOpen/Annotations_DimensionStyleBuilder.hxx>
//#include <NXOpen/Annotations_DimensionWorkflowBuilder.hxx
#include <NXOpen/Annotations_DisplayStyleBuilder.hxx>
//#include <NXOpen/Annotations_DraftingAid.hxx
//#include <NXOpen/Annotations_DraftingArbitraryTarget.hxx
//#include <NXOpen/Annotations_DraftingCustomSymbolBuilder.hxx
//#include <NXOpen/Annotations_DraftingDatum.hxx
//#include <NXOpen/Annotations_DraftingDatumFeatureSymbolBuilder.hxx
//#include <NXOpen/Annotations_DraftingDatumTarget.hxx
//#include <NXOpen/Annotations_DraftingDatumTargetBuilder.hxx
//#include <NXOpen/Annotations_DraftingDatumTargetCollection.hxx
//#include <NXOpen/Annotations_DraftingFcf.hxx
//#include <NXOpen/Annotations_DraftingFeatureControlFrameBuilder.hxx
//#include <NXOpen/Annotations_DraftingImage.hxx
//#include <NXOpen/Annotations_DraftingImageCollection.hxx
//#include <NXOpen/Annotations_DraftingLineTarget.hxx
//#include <NXOpen/Annotations_DraftingNoteBuilder.hxx
//#include <NXOpen/Annotations_DraftingPointTarget.hxx
#include <NXOpen/Annotations_DraftingSurfaceFinish.hxx>
//#include <NXOpen/Annotations_DraftingSurfaceFinishBuilder.hxx
#include <NXOpen/Annotations_DraftingSurfaceFinishCollection.hxx>
//#include <NXOpen/Annotations_DrawingFormatTitleBuilder.hxx
//#include <NXOpen/Annotations_DrivingValueBuilder.hxx
//#include <NXOpen/Annotations_EditLeaderBuilder.hxx
//#include <NXOpen/Annotations_EditSettingsBuilder.hxx
#include <NXOpen/Annotations_EditSymbolDisplayBuilder.hxx>
//#include <NXOpen/Annotations_EditTitleBlockBuilder.hxx
//#include <NXOpen/Annotations_EnterpriseIdentification.hxx
//#include <NXOpen/Annotations_EnterpriseIdentificationBuilder.hxx
//#include <NXOpen/Annotations_ExportControl.hxx
//#include <NXOpen/Annotations_ExportControlBuilder.hxx
//#include <NXOpen/Annotations_Fcf.hxx
//#include <NXOpen/Annotations_FcfCollection.hxx
//#include <NXOpen/Annotations_FcfData.hxx
//#include <NXOpen/Annotations_FcfDatumReference.hxx
//#include <NXOpen/Annotations_FcfFrame.hxx
//#include <NXOpen/Annotations_FcfFrameData.hxx
//#include <NXOpen/Annotations_FeatureControlFrameBuilder.hxx
//#include <NXOpen/Annotations_FeatureControlFrameData.hxx
//#include <NXOpen/Annotations_FeatureControlFrameDataBuilder.hxx
//#include <NXOpen/Annotations_FeatureControlFrameDataBuilderList.hxx
//#include <NXOpen/Annotations_FeatureControlFrameIndicatorBuilder.hxx
//#include <NXOpen/Annotations_FeatureControlFrameIndicatorBuilderList.hxx
//#include <NXOpen/Annotations_FeatureIdBusinessModifier.hxx
//#include <NXOpen/Annotations_FeatureIdBusinessModifierBuilder.hxx
//#include <NXOpen/Annotations_FoldedRadiusDimension.hxx
#include <NXOpen/Annotations_ForeshorteningSymbolBuilder.hxx>
#include <NXOpen/Annotations_ForeshorteningSymbolSettingsBuilder.hxx>
//#include <NXOpen/Annotations_FrameBar.hxx
//#include <NXOpen/Annotations_FrameBarBuilder.hxx
//#include <NXOpen/Annotations_FrameBarCollection.hxx
//#include <NXOpen/Annotations_FrameBarElementStyleBuilder.hxx
//#include <NXOpen/Annotations_FrameBarPreferences.hxx
//#include <NXOpen/Annotations_FrameBarStyleBuilder.hxx
#include <NXOpen/Annotations_Gdt.hxx>
#include <NXOpen/Annotations_GdtCollection.hxx>
//#include <NXOpen/Annotations_GdtDatumCollection.hxx
//#include <NXOpen/Annotations_GeneralArcLengthDimension.hxx
//#include <NXOpen/Annotations_GeneralChamferDimension.hxx
//#include <NXOpen/Annotations_GeneralConcentricCircleDimension.hxx
//#include <NXOpen/Annotations_GeneralCustomSymbol.hxx
//#include <NXOpen/Annotations_GeneralCylindricalDimension.hxx
//#include <NXOpen/Annotations_GeneralDiameterDimension.hxx
//#include <NXOpen/Annotations_GeneralFoldedRadiusDimension.hxx
//#include <NXOpen/Annotations_GeneralHoleDimension.hxx
//#include <NXOpen/Annotations_GeneralHorizontalDimension.hxx
//#include <NXOpen/Annotations_GeneralLabel.hxx
//#include <NXOpen/Annotations_GeneralMajorAngularDimension.hxx
//#include <NXOpen/Annotations_GeneralMinorAngularDimension.hxx
//#include <NXOpen/Annotations_GeneralNote.hxx
//#include <NXOpen/Annotations_GeneralNoteBuilder.hxx
//#include <NXOpen/Annotations_GeneralParallelDimension.hxx
//#include <NXOpen/Annotations_GeneralPerpendicularDimension.hxx
//#include <NXOpen/Annotations_GeneralRadiusDimension.hxx
//#include <NXOpen/Annotations_GeneralVerticalDimension.hxx
//#include <NXOpen/Annotations_GenericNote.hxx
//#include <NXOpen/Annotations_GeodesicDimensionBuilder.hxx
//#include <NXOpen/Annotations_GovernmentSecurityInformation.hxx
//#include <NXOpen/Annotations_GovernmentSecurityInformationBuilder.hxx
#include <NXOpen/Annotations_Hatch.hxx>
#include <NXOpen/Annotations_HatchBuilder.hxx>
#include <NXOpen/Annotations_HatchCollection.hxx>
#include <NXOpen/Annotations_HatchFillSettingsBuilder.hxx>
#include <NXOpen/Annotations_HatchStyleBuilder.hxx>
#include <NXOpen/Annotations_HoleCalloutSettingsBuilder.hxx>
//#include <NXOpen/Annotations_HoleDimension.hxx
//#include <NXOpen/Annotations_HoleTable.hxx
//#include <NXOpen/Annotations_HoleTableBuilder.hxx
//#include <NXOpen/Annotations_HoleTableCollection.hxx
//#include <NXOpen/Annotations_HoleTableSettingsContentBuilder.hxx
//#include <NXOpen/Annotations_HoleTableSettingsFormatBuilder.hxx
//#include <NXOpen/Annotations_HoleTableSettingsHoleFiltersBuilder.hxx
//#include <NXOpen/Annotations_HoleTableSettingsLabelBuilder.hxx
//#include <NXOpen/Annotations_HoleTableSettingsWorkflowBuilder.hxx
//#include <NXOpen/Annotations_HorizontalDimension.hxx
//#include <NXOpen/Annotations_HorizontalOrdinateDimension.hxx
//#include <NXOpen/Annotations_HorizontalOrdinateMargin.hxx
//#include <NXOpen/Annotations_IAngularTolerance.hxx
#include <NXOpen/Annotations_IAppendedText.hxx>
//#include <NXOpen/Annotations_IArbitraryTarget.hxx
//#include <NXOpen/Annotations_ICircularTarget.hxx
//#include <NXOpen/Annotations_IContainer.hxx
//#include <NXOpen/Annotations_IDatum.hxx
//#include <NXOpen/Annotations_IDatumTarget.hxx
#include <NXOpen/Annotations_IdSymbol.hxx>
//#include <NXOpen/Annotations_IdSymbolBuilder.hxx
#include <NXOpen/Annotations_IdSymbolCollection.hxx>
//#include <NXOpen/Annotations_IFcf.hxx
//#include <NXOpen/Annotations_ILinearTolerance.hxx
//#include <NXOpen/Annotations_ILineTarget.hxx
//#include <NXOpen/Annotations_ImportAutocadBlockBuilder.hxx
//#include <NXOpen/Annotations_ImportSymbolBuilder.hxx
#include <NXOpen/Annotations_IntersectionSymbol.hxx>
//#include <NXOpen/Annotations_IntersectionSymbolBuilder.hxx
#include <NXOpen/Annotations_IntersectionSymbolCollection.hxx>
#include <NXOpen/Annotations_IPmi.hxx>
//#include <NXOpen/Annotations_IPointTarget.hxx
//#include <NXOpen/Annotations_IRectangularTarget.hxx
//#include <NXOpen/Annotations_ISlotDimension.hxx
#include <NXOpen/Annotations_Label.hxx>
#include <NXOpen/Annotations_LabelCollection.hxx>
//#include <NXOpen/Annotations_LabelData.hxx
//#include <NXOpen/Annotations_LeaderBuilder.hxx
//#include <NXOpen/Annotations_LeaderBundle.hxx
//#include <NXOpen/Annotations_LeaderData.hxx
//#include <NXOpen/Annotations_LeaderDataList.hxx
#include <NXOpen/Annotations_LetteringPreferences.hxx>
#include <NXOpen/Annotations_LetteringStyleBuilder.hxx>
//#include <NXOpen/Annotations_LightweightSection.hxx
//#include <NXOpen/Annotations_LightweightSectionBuilder.hxx
//#include <NXOpen/Annotations_LightweightSectionView.hxx
//#include <NXOpen/Annotations_LineAndArrowPreferences.hxx
//#include <NXOpen/Annotations_LinearDimensionBuilder.hxx
#include <NXOpen/Annotations_LineArrowStyleBuilder.hxx>
//#include <NXOpen/Annotations_LinearTolerance.hxx
//#include <NXOpen/Annotations_LineComponent.hxx
//#include <NXOpen/Annotations_LineTarget.hxx
//#include <NXOpen/Annotations_LineWeld.hxx
//#include <NXOpen/Annotations_LineWeldBuilder.hxx
//#include <NXOpen/Annotations_LineWeldData.hxx
//#include <NXOpen/Annotations_LineWeldDataBuilder.hxx
//#include <NXOpen/Annotations_LineWeldSideData.hxx
//#include <NXOpen/Annotations_ListBusinessModifier.hxx
//#include <NXOpen/Annotations_LocatorDesignator.hxx
//#include <NXOpen/Annotations_LocatorDesignatorBuilder.hxx
//#include <NXOpen/Annotations_MajorAngularDimension.hxx
//#include <NXOpen/Annotations_MajorAngularDimensionBuilder.hxx
//#include <NXOpen/Annotations_MasterCustomSymbol.hxx
//#include <NXOpen/Annotations_MasterCustomSymbolData.hxx
//#include <NXOpen/Annotations_MasterSymbol.hxx
//#include <NXOpen/Annotations_MasterSymbolBuilder.hxx
//#include <NXOpen/Annotations_MasterSymbolListItemBuilder.hxx
//#include <NXOpen/Annotations_MasterSymbolListItemBuilderList.hxx
//#include <NXOpen/Annotations_MaterialSpecification.hxx
//#include <NXOpen/Annotations_MaterialSpecificationBuilder.hxx
//#include <NXOpen/Annotations_MinorAngularDimension.hxx
//#include <NXOpen/Annotations_MinorAngularDimensionBuilder.hxx
#include <NXOpen/Annotations_NarrowDimensionPreferences.hxx>
#include <NXOpen/Annotations_Note.hxx>
#include <NXOpen/Annotations_NoteBase.hxx>
#include <NXOpen/Annotations_NoteCollection.hxx>
//#include <NXOpen/Annotations_NoteData.hxx
#include <NXOpen/Annotations_OffsetCenterPoint.hxx>
//#include <NXOpen/Annotations_OffsetCenterPointBuilder.hxx
#include <NXOpen/Annotations_OffsetCenterPointCollection.hxx>
//#include <NXOpen/Annotations_OrdinateBaselineBuilder.hxx
//#include <NXOpen/Annotations_OrdinateDimension.hxx
//#include <NXOpen/Annotations_OrdinateDimensionBuilder.hxx
#include <NXOpen/Annotations_OrdinateDimensionPreferences.hxx>
//#include <NXOpen/Annotations_OrdinateMargin.hxx
//#include <NXOpen/Annotations_OrdinateMarginCollection.hxx
//#include <NXOpen/Annotations_OrdinateOriginDimension.hxx
//#include <NXOpen/Annotations_OrdinateStyleBuilder.hxx
#include <NXOpen/Annotations_OriginBuilder.hxx>
//#include <NXOpen/Annotations_ParallelDimension.hxx
//#include <NXOpen/Annotations_PartIdentification.hxx
//#include <NXOpen/Annotations_PartIdentificationBuilder.hxx
#include <NXOpen/Annotations_PartsList.hxx>
//#include <NXOpen/Annotations_PartsListBuilder.hxx
//#include <NXOpen/Annotations_PartSymbolFolder.hxx
//#include <NXOpen/Annotations_PartSymbolFolderBuilder.hxx
//#include <NXOpen/Annotations_PartSymbolFolderCollection.hxx
//#include <NXOpen/Annotations_PerpendicularDimension.hxx
//#include <NXOpen/Annotations_PinListBuilder.hxx
//#include <NXOpen/Annotations_PlaneBuilder.hxx
#include <NXOpen/Annotations_Pmi.hxx>
//#include <NXOpen/Annotations_PmiAngularDimension.hxx
//#include <NXOpen/Annotations_PmiAngularDimensionBuilder.hxx
//#include <NXOpen/Annotations_PmiArcLengthDimension.hxx
//#include <NXOpen/Annotations_PmiAttribute.hxx
//#include <NXOpen/Annotations_PmiAttributeBuilder.hxx
//#include <NXOpen/Annotations_PmiAttributeCollection.hxx
//#include <NXOpen/Annotations_PmiAttributeValue.hxx
//#include <NXOpen/Annotations_PmiAttributeValueInteger.hxx
//#include <NXOpen/Annotations_PmiAttributeValueIntegerBuilder.hxx
//#include <NXOpen/Annotations_PmiAttributeValueList.hxx
//#include <NXOpen/Annotations_PmiAttributeValueListBuilder.hxx
//#include <NXOpen/Annotations_PmiAttributeValueMultipleString.hxx
//#include <NXOpen/Annotations_PmiAttributeValueMultipleStringBuilder.hxx
//#include <NXOpen/Annotations_PmiAttributeValueNumber.hxx
//#include <NXOpen/Annotations_PmiAttributeValueNumberBuilder.hxx
//#include <NXOpen/Annotations_PmiAttributeValueString.hxx
//#include <NXOpen/Annotations_PmiAttributeValueStringBuilder.hxx
//#include <NXOpen/Annotations_PmiAttributeValueUrl.hxx
//#include <NXOpen/Annotations_PmiAttributeValueUrlBuilder.hxx
//#include <NXOpen/Annotations_PmiBaselineDimension.hxx
//#include <NXOpen/Annotations_PmiBoltCircleCenterline.hxx
//#include <NXOpen/Annotations_PmiBoltCircleCenterlineBuilder.hxx
//#include <NXOpen/Annotations_PmiCenterline3d.hxx
//#include <NXOpen/Annotations_PmiCenterline3dBuilder.hxx
//#include <NXOpen/Annotations_PmiCenterMark.hxx
//#include <NXOpen/Annotations_PmiCenterMarkBuilder.hxx
//#include <NXOpen/Annotations_PmiChainDimension.hxx
//#include <NXOpen/Annotations_PmiChamferDimension.hxx
//#include <NXOpen/Annotations_PmiChamferDimensionBuilder.hxx
//#include <NXOpen/Annotations_PmiCollection.hxx
//#include <NXOpen/Annotations_PmiConcentricCircleDimension.hxx
//#include <NXOpen/Annotations_PmiCurveLengthDimensionBuilder.hxx
//#include <NXOpen/Annotations_PmiCustomSymbol.hxx
//#include <NXOpen/Annotations_PmiCustomSymbolBuilder.hxx
//#include <NXOpen/Annotations_PmiCylindricalDimension.hxx
//#include <NXOpen/Annotations_PmiData.hxx
//#include <NXOpen/Annotations_PmiDatumFeatureSymbolBuilder.hxx
//#include <NXOpen/Annotations_PmiDatumTargetBuilder.hxx
//#include <NXOpen/Annotations_PmiDiameterDimension.hxx
//#include <NXOpen/Annotations_PMIExplicitOrderBuilder.hxx
//#include <NXOpen/Annotations_PmiFeatureControlFrameBuilder.hxx
//#include <NXOpen/Annotations_PmiFilter.hxx
//#include <NXOpen/Annotations_PmiFilterByPart.hxx
//#include <NXOpen/Annotations_PmiFilterByType.hxx
//#include <NXOpen/Annotations_PmiFilterByView.hxx
//#include <NXOpen/Annotations_PmiFilterCollection.hxx
//#include <NXOpen/Annotations_PmiFoldedRadiusDimension.hxx
//#include <NXOpen/Annotations_PmiHoleDimension.hxx
//#include <NXOpen/Annotations_PmiHorizontalDimension.hxx
//#include <NXOpen/Annotations_PmiHorizontalOrdinateDimension.hxx
//#include <NXOpen/Annotations_PmiInteger.hxx
//#include <NXOpen/Annotations_PmiIntegerBuilder.hxx
//#include <NXOpen/Annotations_PmiLabel.hxx
//#include <NXOpen/Annotations_PmiLightweightSectionCollection.hxx
//#include <NXOpen/Annotations_PmiLinearDimensionBuilder.hxx
//#include <NXOpen/Annotations_PmiLineWeld.hxx
//#include <NXOpen/Annotations_PmiLineWeldBuilder.hxx
//#include <NXOpen/Annotations_PmiMajorAngularDimension.hxx
//#include <NXOpen/Annotations_PmiMajorAngularDimensionBuilder.hxx
//#include <NXOpen/Annotations_PmiManager.hxx
//#include <NXOpen/Annotations_PmiMinorAngularDimension.hxx
//#include <NXOpen/Annotations_PmiMinorAngularDimensionBuilder.hxx
//#include <NXOpen/Annotations_PmiNote.hxx
#include <NXOpen/Annotations_PmiNoteBuilder.hxx>
//#include <NXOpen/Annotations_PmiNumber.hxx
//#include <NXOpen/Annotations_PmiNumberBuilder.hxx
//#include <NXOpen/Annotations_PmiOrdinateDimensionBuilder.hxx
//#include <NXOpen/Annotations_PmiOrdinateOriginDimension.hxx
//#include <NXOpen/Annotations_PmiParallelDimension.hxx
//#include <NXOpen/Annotations_PmiPerpendicularDimension.hxx
#include <NXOpen/Annotations_PmiPreferences.hxx>
//#include <NXOpen/Annotations_PmiRadialDimensionBuilder.hxx
//#include <NXOpen/Annotations_PmiRadiusDimension.hxx
//#include <NXOpen/Annotations_PmiRapidDimensionBuilder.hxx
#include <NXOpen/Annotations_PmiRegionCollection.hxx>
//#include <NXOpen/Annotations_PmiString.hxx
//#include <NXOpen/Annotations_PmiStringBuilder.hxx
#include <NXOpen/Annotations_PmiTableBuilder.hxx>
//#include <NXOpen/Annotations_PmiTableSection.hxx
//#include <NXOpen/Annotations_PmiTableSectionCollection.hxx
//#include <NXOpen/Annotations_PmiThicknessDimensionBuilder.hxx
//#include <NXOpen/Annotations_PmiTrackingPropertiesBuilder.hxx
//#include <NXOpen/Annotations_PmiUrlNote.hxx
//#include <NXOpen/Annotations_PmiUrlNoteBuilder.hxx
//#include <NXOpen/Annotations_PmiUserDefined.hxx
//#include <NXOpen/Annotations_PmiUserDefinedBuilder.hxx
//#include <NXOpen/Annotations_PmiVerticalDimension.hxx
//#include <NXOpen/Annotations_PmiVerticalOrdinateDimension.hxx
//#include <NXOpen/Annotations_PmiWave.hxx
//#include <NXOpen/Annotations_PmiWaveCollection.hxx
//#include <NXOpen/Annotations_PmiWaveLinkBuilder.hxx
//#include <NXOpen/Annotations_PointTarget.hxx
//#include <NXOpen/Annotations_ProcessSpecification.hxx
//#include <NXOpen/Annotations_ProcessSpecificationBuilder.hxx
//#include <NXOpen/Annotations_QueryPmiBuilder.hxx
//#include <NXOpen/Annotations_RadialDimensionBuilder.hxx
//#include <NXOpen/Annotations_RadialStyleBuilder.hxx
//#include <NXOpen/Annotations_RadiusDimension.hxx
//#include <NXOpen/Annotations_RapidDimensionBuilder.hxx
//#include <NXOpen/Annotations_RectangularTarget.hxx
//#include <NXOpen/Annotations_RectangularTargetData.hxx
#include <NXOpen/Annotations_Region.hxx>
#include <NXOpen/Annotations_RegionBuilder.hxx>
//#include <NXOpen/Annotations_ReplaceSymbolBuilder.hxx
//#include <NXOpen/Annotations_RetainedAnnotationsBuilder.hxx
//#include <NXOpen/Annotations_RevisionBusinessModifier.hxx
//#include <NXOpen/Annotations_RevisionBusinessModifierBuilder.hxx
//#include <NXOpen/Annotations_SafetyClassBusinessModifier.hxx
//#include <NXOpen/Annotations_SafetyClassBusinessModifierBuilder.hxx
//#include <NXOpen/Annotations_SearchCriteriaCalloutBuilder.hxx
//#include <NXOpen/Annotations_SearchCriteriaDatumFeatureSymbolBuilder.hxx
//#include <NXOpen/Annotations_SearchCriteriaDatumTargetBuilder.hxx
//#include <NXOpen/Annotations_SearchCriteriaDimensionBuilder.hxx
//#include <NXOpen/Annotations_SearchCriteriaFeatureControlFrameBuilder.hxx
//#include <NXOpen/Annotations_SearchCriteriaPMINotesBuilder.hxx
//#include <NXOpen/Annotations_SearchCriteriaSurfaceFinishBuilder.hxx
//#include <NXOpen/Annotations_SearchModelView.hxx
//#include <NXOpen/Annotations_SearchModelViewBuilder.hxx
//#include <NXOpen/Annotations_SearchModelViewCollection.hxx
//#include <NXOpen/Annotations_SelectAnnotation.hxx
//#include <NXOpen/Annotations_SelectAnnotationList.hxx
//#include <NXOpen/Annotations_SelectBaseCustomSymbolList.hxx
//#include <NXOpen/Annotations_SelectDimension.hxx
//#include <NXOpen/Annotations_SelectOrdinateDimensionList.hxx
//#include <NXOpen/Annotations_SelectTableSectionList.hxx
//#include <NXOpen/Annotations_ShipDimensionBuilder.hxx
//#include <NXOpen/Annotations_ShipDimensionCollection.hxx
//#include <NXOpen/Annotations_ShipDraftingFramebarGeneralBuilder.hxx
//#include <NXOpen/Annotations_SimpleDraftingAid.hxx
//#include <NXOpen/Annotations_SimpleDraftingAidPreferences.hxx>
#include <NXOpen/Annotations_SingleSidedDisplayBuilder.hxx>
//#include <NXOpen/Annotations_SmashCustomSymbolBuilder.hxx
//#include <NXOpen/Annotations_SpecificNote.hxx
//#include <NXOpen/Annotations_SpecificNoteBuilder.hxx
#include <NXOpen/Annotations_StyleBuilder.hxx>
//#include <NXOpen/Annotations_SuppressPMIBuilder.hxx
#include <NXOpen/Annotations_SurfaceFinish.hxx>
#include <NXOpen/Annotations_SurfaceFinishBuilder.hxx>
//#include <NXOpen/Annotations_SymbolCatalogBuilder.hxx
//#include <NXOpen/Annotations_SymbolCatalogParameterBuilder.hxx
//#include <NXOpen/Annotations_SymbolCatalogParameterBuilderList.hxx
//#include <NXOpen/Annotations_SymbolFile.hxx
//#include <NXOpen/Annotations_SymbolFileBuilder.hxx
//#include <NXOpen/Annotations_SymbolFileCollection.hxx
#include <NXOpen/Annotations_SymbolPreferences.hxx>
//#include <NXOpen/Annotations_SymbolStyleBuilder.hxx
//#include <NXOpen/Annotations_SymbolWorkflowBuilder.hxx
//#include <NXOpen/Annotations_SymmetricalCenterline.hxx
//#include <NXOpen/Annotations_SymmetricalCenterlineBuilder.hxx
//#include <NXOpen/Annotations_SymmetricalCenterlineSettingsBuilder.hxx
//#include <NXOpen/Annotations_Table.hxx
//#include <NXOpen/Annotations_TableCellStyleBuilder.hxx
//#include <NXOpen/Annotations_TableCollection.hxx
//#include <NXOpen/Annotations_TableColumnBuilder.hxx
//#include <NXOpen/Annotations_TableEditSettingsBuilder.hxx
//#include <NXOpen/Annotations_TableSection.hxx
//#include <NXOpen/Annotations_TableSectionBuilder.hxx
//#include <NXOpen/Annotations_TableSectionCollection.hxx
//#include <NXOpen/Annotations_TableSectionStyleBuilder.hxx
//#include <NXOpen/Annotations_TableStyleBuilder.hxx
//#include <NXOpen/Annotations_TabularNoteStyleBuilder.hxx
//#include <NXOpen/Annotations_TargetPoint.hxx
//#include <NXOpen/Annotations_TargetPointBuilder.hxx
//#include <NXOpen/Annotations_TargetPointCollection.hxx
#include <NXOpen/Annotations_TextComponent.hxx>
#include <NXOpen/Annotations_TextWithEditControlsBuilder.hxx>
#include <NXOpen/Annotations_TextWithSymbolsBuilder.hxx>
//#include <NXOpen/Annotations_ThicknessDimensionBuilder.hxx
//#include <NXOpen/Annotations_TitleBlock.hxx
//#include <NXOpen/Annotations_TitleBlockCellBuilder.hxx
//#include <NXOpen/Annotations_TitleBlockCellBuilderList.hxx
//#include <NXOpen/Annotations_TitleBlockCollection.hxx
//#include <NXOpen/Annotations_TitleBlockPreferences.hxx
#include <NXOpen/Annotations_UnitsFormatPreferences.hxx>
#include <NXOpen/Annotations_UnitsStyleBuilder.hxx>
//#include <NXOpen/Annotations_UrlBusinessModifier.hxx
//#include <NXOpen/Annotations_UrlBusinessModifierBuilder.hxx
#include <NXOpen/Annotations_UserSymbolPreferences.hxx>
//#include <NXOpen/Annotations_VerticalDimension.hxx
//#include <NXOpen/Annotations_VerticalOrdinateDimension.hxx
//#include <NXOpen/Annotations_VerticalOrdinateMargin.hxx
#include <NXOpen/Annotations_Weld.hxx>
#include <NXOpen/Annotations_WeldCollection.hxx>
#include <NXOpen/CAE_PostAnnotationPreference.hxx>
//#include <NXOpen/DiagrammingDebugSession.hxx
//#include <NXOpen/DiagrammingLibraryAuthor_AttributeHolder.hxx
//#include <NXOpen/DiagrammingLibraryAuthor_LineTypeBuilder.hxx
//#include <NXOpen/DiagrammingLibraryAuthor_LineTypeBuilderList.hxx
//#include <NXOpen/DiagrammingLibraryAuthor_PipeStockBuilder.hxx
//#include <NXOpen/DiagrammingLibraryAuthor_PortDataBuilder.hxx
//#include <NXOpen/DiagrammingLibraryAuthor_Symbol2DBuilder.hxx
//#include <NXOpen/DiagrammingLibraryAuthor_Symbol3DBuilder.hxx
//#include <NXOpen/Diagramming_Annotation.hxx
//#include <NXOpen/Diagramming_AnnotationBuilder.hxx
//#include <NXOpen/Diagramming_AnnotationCollection.hxx
//#include <NXOpen/Diagramming_BaseObject.hxx
//#include <NXOpen/Diagramming_BaseObjectBuilder.hxx
//#include <NXOpen/Diagramming_BaseSubObjectBuilder.hxx
//#include <NXOpen/Diagramming_BaseTaggedObjectBuilder.hxx
//#include <NXOpen/Diagramming_BordersAndZones.hxx
//#include <NXOpen/Diagramming_BulkEditBuilder.hxx
//#include <NXOpen/Diagramming_CannedAnnotationBuilder.hxx
//#include <NXOpen/Diagramming_ConnectableElement.hxx
//#include <NXOpen/Diagramming_ConnectableElementBuilder.hxx
//#include <NXOpen/Diagramming_Connection.hxx
//#include <NXOpen/Diagramming_ConnectionBuilder.hxx
//#include <NXOpen/Diagramming_ConnectionCollection.hxx
//#include <NXOpen/Diagramming_ConnectionLocationBuilder.hxx
//#include <NXOpen/Diagramming_ConnectionLocationBuilderList.hxx
//#include <NXOpen/Diagramming_DataType.hxx
//#include <NXOpen/Diagramming_DefineTitleBlockBuilder.hxx
//#include <NXOpen/Diagramming_DiagrammingManager.hxx
//#include <NXOpen/Diagramming_DiagrammingTestManager.hxx
//#include <NXOpen/Diagramming_EquipmentBuilder.hxx
//#include <NXOpen/Diagramming_FormattedStringBuilder.hxx
//#include <NXOpen/Diagramming_Group.hxx
//#include <NXOpen/Diagramming_GroupBuilder.hxx
//#include <NXOpen/Diagramming_GroupCollection.hxx
//#include <NXOpen/Diagramming_LeaderLine.hxx
//#include <NXOpen/Diagramming_LeaderLineBuilder.hxx
//#include <NXOpen/Diagramming_LeaderLineBuilderList.hxx
//#include <NXOpen/Diagramming_LeaderLineCollection.hxx
//#include <NXOpen/Diagramming_LocationBuilder.hxx
//#include <NXOpen/Diagramming_Node.hxx
//#include <NXOpen/Diagramming_NodeBuilder.hxx
//#include <NXOpen/Diagramming_NodeCollection.hxx
//#include <NXOpen/Diagramming_PipeBuilder.hxx
//#include <NXOpen/Diagramming_PopulateTitleBlockBuilder.hxx
//#include <NXOpen/Diagramming_Port.hxx
//#include <NXOpen/Diagramming_PortBuilder.hxx
//#include <NXOpen/Diagramming_PortBuilderList.hxx
//#include <NXOpen/Diagramming_PortCollection.hxx
//#include <NXOpen/Diagramming_RenderingPropertiesBuilder.hxx
//#include <NXOpen/Diagramming_Shape.hxx
//#include <NXOpen/Diagramming_ShapeBuilder.hxx
//#include <NXOpen/Diagramming_ShapeCollection.hxx
//#include <NXOpen/Diagramming_Sheet.hxx
//#include <NXOpen/Diagramming_SheetBordersAndZones.hxx
//#include <NXOpen/Diagramming_SheetBordersAndZonesBuilder.hxx
//#include <NXOpen/Diagramming_SheetBordersAndZonesCollection.hxx
//#include <NXOpen/Diagramming_SheetBorderSettingsBuilder.hxx
//#include <NXOpen/Diagramming_SheetBuilder.hxx
//#include <NXOpen/Diagramming_SheetCollection.hxx
//#include <NXOpen/Diagramming_SheetElement.hxx
//#include <NXOpen/Diagramming_SheetElementBuilder.hxx
//#include <NXOpen/Diagramming_SheetManager.hxx
//#include <NXOpen/Diagramming_SheetMarginSettingsBuilder.hxx
//#include <NXOpen/Diagramming_SheetZoneSettingsBuilder.hxx
//#include <NXOpen/Diagramming_Tables_CellBuilder.hxx
//#include <NXOpen/Diagramming_Tables_CellRangeBuilder.hxx
//#include <NXOpen/Diagramming_Tables_CellSettingsBuilder.hxx
//#include <NXOpen/Diagramming_Tables_ColumnBuilder.hxx
//#include <NXOpen/Diagramming_Tables_ContinuationDataBuilder.hxx
//#include <NXOpen/Diagramming_Tables_RowBuilder.hxx
//#include <NXOpen/Diagramming_Tables_Table.hxx
//#include <NXOpen/Diagramming_Tables_TableBuilder.hxx
//#include <NXOpen/Diagramming_Tables_TableCollection.hxx
//#include <NXOpen/Diagramming_Tables_TableSettingsBuilder.hxx
//#include <NXOpen/Diagramming_Tables_Types.hxx
//#include <NXOpen/Diagramming_TextStyleBuilder.hxx
//#include <NXOpen/Diagramming_TitleBlock.hxx
//#include <NXOpen/Diagramming_TitleBlockCellBuilder.hxx
//#include <NXOpen/Diagramming_TitleBlockCollection.hxx
#include <NXOpen/Dimensions.hxx>
#include <NXOpen/Direction.hxx>
#include <NXOpen/DirectionCollection.hxx>
//#include <NXOpen/Display_Background.hxx
//#include <NXOpen/Display_BoundedGrid.hxx
//#include <NXOpen/Display_BoundedGridBuilder.hxx
//#include <NXOpen/Display_Camera.hxx
//#include <NXOpen/Display_CameraBuilder.hxx
//#include <NXOpen/Display_CameraCollection.hxx
//#include <NXOpen/Display_CanonMRTestBuilder.hxx
//#include <NXOpen/Display_CgfxAttr.hxx
//#include <NXOpen/Display_CgfxAttrCollection.hxx
#include <NXOpen/Display_CgfxAttributeValueColor3Builder.hxx>
#include <NXOpen/Display_CgfxAttributeValueColor4Builder.hxx>
//#include <NXOpen/Display_CgfxAttributeValueFileBuilder.hxx
//#include <NXOpen/Display_CgfxAttributeValueFloat3Builder.hxx
//#include <NXOpen/Display_CgfxAttributeValueFloat4Builder.hxx
//#include <NXOpen/Display_CgfxAttributeValueIntegerBuilder.hxx
//#include <NXOpen/Display_CgfxAttributeValueNumberBuilder.hxx
//#include <NXOpen/Display_CgfxMattex.hxx
//#include <NXOpen/Display_CgfxMattexBuilder.hxx
//#include <NXOpen/Display_CgfxMattexCollection.hxx
//#include <NXOpen/Display_DatumPlaneGrid.hxx
//#include <NXOpen/Display_DatumPlaneGridBuilder.hxx
//#include <NXOpen/Display_DecalBuilder.hxx
//#include <NXOpen/Display_DecalCollection.hxx
//#include <NXOpen/Display_DynamicSection.hxx
//#include <NXOpen/Display_DynamicSectionBuilder.hxx
//#include <NXOpen/Display_DynamicSectionCollection.hxx
//#include <NXOpen/Display_DynamicSectionCut.hxx
//#include <NXOpen/Display_DynamicSectionTypes.hxx
//#include <NXOpen/Display_EntitySelectionPlane.hxx
//#include <NXOpen/Display_EnvironmentBuilder.hxx
//#include <NXOpen/Display_ExtractScene.hxx
//#include <NXOpen/Display_FacetSettingsBuilder.hxx
//#include <NXOpen/Display_GlobalIlluminationBuilder.hxx
//#include <NXOpen/Display_Grid.hxx
//#include <NXOpen/Display_GridBuilder.hxx
//#include <NXOpen/Display_GridCollection.hxx
//#include <NXOpen/Display_IDynamicSectionCutCreator.hxx
//#include <NXOpen/Display_Image.hxx
//#include <NXOpen/Display_ImageBase.hxx
//#include <NXOpen/Display_ImageBaseBuilder.hxx
//#include <NXOpen/Display_ImageBasedLighting.hxx
//#include <NXOpen/Display_ImageCollection.hxx
//#include <NXOpen/Display_ImageData.hxx
//#include <NXOpen/Display_ImageDataCollection.hxx
//#include <NXOpen/Display_ImageTestBuilder.hxx
//#include <NXOpen/Display_IrayPlusMaterialAttribute.hxx
//#include <NXOpen/Display_IrayPlusMaterialAttributeEnum.hxx
//#include <NXOpen/Display_IrayPlusMaterialEditorBuilder.hxx
//#include <NXOpen/Display_IrayPlusSimpleMaterialEditorBuilder.hxx
//#include <NXOpen/Display_IRayPlusStudioEditorBuilder.hxx
#include <NXOpen/Display_LayerSettingsBuilder.hxx>
//#include <NXOpen/Display_LightBuilder.hxx
//#include <NXOpen/Display_Lighting.hxx
//#include <NXOpen/Display_LightTypes.hxx
//#include <NXOpen/Display_NonProportionalZoom.hxx
//#include <NXOpen/Display_PerspectiveOptionsBuilder.hxx>
//#include <NXOpen/Display_PlanarShipGrid.hxx
//#include <NXOpen/Display_PlanarShipGridBuilder.hxx
//#include <NXOpen/Display_PlaneGrid.hxx
//#include <NXOpen/Display_PlaneGridBuilder.hxx
//#include <NXOpen/Display_PointCloud.hxx
//#include <NXOpen/Display_PointCloudBuilder.hxx
//#include <NXOpen/Display_PointCloudClippingBoxesListItemBuilder.hxx
//#include <NXOpen/Display_PointCloudClippingBoxesListItemBuilderList.hxx
//#include <NXOpen/Display_PointCloudCollection.hxx
//#include <NXOpen/Display_RasterImage.hxx
//#include <NXOpen/Display_RasterImageBuilder.hxx
//#include <NXOpen/Display_RayTracedStudioBuilder.hxx
//#include <NXOpen/Display_RayTracedStudioEditorBuilder.hxx
//#include <NXOpen/Display_Reflection.hxx
//#include <NXOpen/Display_SaveImageFileBrowserBuilder.hxx
//#include <NXOpen/Display_Scene.hxx
//#include <NXOpen/Display_SectionCurveSettingsBuilder.hxx
//#include <NXOpen/Display_SelectFontFileBuilder.hxx
//#include <NXOpen/Display_SelPref.hxx
//#include <NXOpen/Display_SelPrefCollection.hxx
//#include <NXOpen/Display_Shadows.hxx
//#include <NXOpen/Display_Stage.hxx
//#include <NXOpen/Display_StudioImageCaptureBuilder.hxx
#include <NXOpen/Display_TransientText.hxx>
//#include <NXOpen/Display_TrueShading.hxx
//#include <NXOpen/Display_TrueShadingBuilder.hxx
//#include <NXOpen/Display_TrueShadingCollection.hxx
//#include <NXOpen/Display_TrueStudio.hxx
//#include <NXOpen/Display_TrueStudioBuilder.hxx
//#include <NXOpen/Display_TrueStudioCollection.hxx
//#include <NXOpen/Display_Wall.hxx
#include <NXOpen/DisplayableObject.hxx>
#include <NXOpen/DisplayManager.hxx>
//#include <NXOpen/DraftingAutotestPrint.hxx
//#include <NXOpen/DraftingCollectionValidator.hxx
//#include <NXOpen/DraftingDebugSession.hxx
//#include <NXOpen/DraftingDebugTool.hxx
#include <NXOpen/DraftingManager.hxx>
//#include <NXOpen/Drafting_AnnotateViewsBuilder.hxx
//#include <NXOpen/Drafting_AttributeItemBuilder.hxx
//#include <NXOpen/Drafting_AttributeItemBuilderList.hxx
#include <NXOpen/Drafting_AutomationManager.hxx>
//#include <NXOpen/Drafting_AutomationPreferencesBuilder.hxx
//#include <NXOpen/Drafting_AutomationRuleBuilder.hxx
//#include <NXOpen/Drafting_BaseEditSettingsBuilder.hxx
//#include <NXOpen/Drafting_CutCopyPasteBuilder.hxx
//#include <NXOpen/Drafting_CutCopyPasteLeaderBuilder.hxx
//#include <NXOpen/Drafting_DistributeAnnotationsBuilder.hxx
#include <NXOpen/Drafting_DraftingApplicationManager.hxx>
//#include <NXOpen/Drafting_DrawingAutomationWizard.hxx
#include <NXOpen/Drafting_DrawingCreationWizardBuilder.hxx>
//#include <NXOpen/Drafting_MoveToDrawingViewBuilder.hxx
#include <NXOpen/Drafting_PreferencesBuilder.hxx>
#include <NXOpen/Drafting_PrimaryContentItemBuilder.hxx>
//#include <NXOpen/Drafting_PrimaryContentItemBuilderList.hxx
//#include <NXOpen/Drafting_RulesBuilder.hxx
#include <NXOpen/Drafting_SettingsManager.hxx>
//#include <NXOpen/Drafting_SmashDrawingViewBuilder.hxx
//#include <NXOpen/Drafting_SpecifyRuleBuilder.hxx
//#include <NXOpen/DraftPointDataCollection.hxx
//#include <NXOpen/DraftTemplateTestManager.hxx
//#include <NXOpen/DraftUITemplateTestManager.hxx
//#include <NXOpen/DrawingCompareManager.hxx
//#include <NXOpen/Drawings_AddObjectsToRegionBuilder.hxx
//#include <NXOpen/Drawings_AddRemoveBoxViewBuilder.hxx
//#include <NXOpen/Drawings_AnnotationSettingsBuilder.hxx
//#include <NXOpen/Drawings_AssociativeAngleBuilder.hxx
#include <NXOpen/Drawings_AutomationBookletBuilder.hxx>
#include <NXOpen/Drawings_AutomationTemplateRegionBuilder.hxx>
//#include <NXOpen/Drawings_BaseHalfSectionLine.hxx
//#include <NXOpen/Drawings_BasePointToPointSectionLine.hxx
//#include <NXOpen/Drawings_BaseSteppedSectionLine.hxx
#include <NXOpen/Drawings_BaseView.hxx>
#include <NXOpen/Drawings_BaseViewBuilder.hxx>
//#include <NXOpen/Drawings_BaseViewStyle.hxx
//#include <NXOpen/Drawings_BorderAndZoneStyleBuilder.hxx
//#include <NXOpen/Drawings_BordersAndZones.hxx
//#include <NXOpen/Drawings_BordersAndZonesBuilder.hxx
//#include <NXOpen/Drawings_BordersAndZonesCollection.hxx
//#include <NXOpen/Drawings_BrokenViewBuilder.hxx
//#include <NXOpen/Drawings_CompareReportBuilder.hxx
//#include <NXOpen/Drawings_ConversionProcessSettingsBuilder.hxx
//#include <NXOpen/Drawings_ConvertDraftingContentsBuilder.hxx
#include <NXOpen/Drawings_ConvertToPMIBuilderManager.hxx>
//#include <NXOpen/Drawings_CustomViewSettingsBuilder.hxx
#include <NXOpen/Drawings_DetailView.hxx>
#include <NXOpen/Drawings_DetailViewBuilder.hxx>
//#include <NXOpen/Drawings_DraftingBody.hxx
//#include <NXOpen/Drawings_DraftingBodyCollection.hxx
//#include <NXOpen/Drawings_DraftingComponentSelectionBuilder.hxx
//#include <NXOpen/Drawings_DraftingCurve.hxx
//#include <NXOpen/Drawings_DraftingCurveCollection.hxx
//#include <NXOpen/Drawings_DraftingCurveInfo.hxx
//#include <NXOpen/Drawings_DraftingDrawingSheet.hxx
#include <NXOpen/Drawings_DraftingDrawingSheetBuilder.hxx>
#include <NXOpen/Drawings_DraftingDrawingSheetCollection.hxx>
//#include <NXOpen/Drawings_DraftingPoint.hxx
//#include <NXOpen/Drawings_DraftingPointCollection.hxx
#include <NXOpen/Drawings_DraftingView.hxx>
#include <NXOpen/Drawings_DraftingViewCollection.hxx>
//#include <NXOpen/Drawings_DrawingCompareSettingsBuilder.hxx
#include <NXOpen/Drawings_DrawingFormatSheetBuilder.hxx>
#include <NXOpen/Drawings_DrawingRegion.hxx>
#include <NXOpen/Drawings_DrawingRegionBuilder.hxx>
#include <NXOpen/Drawings_DrawingRegionCollection.hxx>
#include <NXOpen/Drawings_DrawingRegionRulesBuilder.hxx>
#include <NXOpen/Drawings_DrawingSheet.hxx>
//#include <NXOpen/Drawings_DrawingSheetBuilder.hxx
#include <NXOpen/Drawings_DrawingSheetCollection.hxx>
//#include <NXOpen/Drawings_DrawingsPropertiesBuilder.hxx
#include <NXOpen/Drawings_DrawingView.hxx>
#include <NXOpen/Drawings_DrawingViewBuilder.hxx>
#include <NXOpen/Drawings_EditSectionLineSettingsBuilder.hxx>
//#include <NXOpen/Drawings_EditViewLabelSettingsBuilder.hxx
#include <NXOpen/Drawings_EditViewSettingsBuilder.hxx>
//#include <NXOpen/Drawings_FlatPatternObject.hxx
//#include <NXOpen/Drawings_FlatPatternViewStyle.hxx>
#include <NXOpen/Drawings_GeneralViewStyle.hxx>
//#include <NXOpen/Drawings_GeneralWorkFlowBuilder.hxx
//#include <NXOpen/Drawings_HalfPictorialSectionLine.hxx
//#include <NXOpen/Drawings_HalfSectionLine.hxx
//#include <NXOpen/Drawings_HalfSectionLineBuilder.hxx
#include <NXOpen/Drawings_HiddenLinesViewStyle.hxx>
//#include <NXOpen/Drawings_HiddenObjectsBuilder.hxx
//#include <NXOpen/Drawings_HingeLineBuilder.hxx
#include <NXOpen/Drawings_InheritPmiViewStyle.hxx>
//#include <NXOpen/Drawings_MarkAsTemplateBuilder.hxx
//#include <NXOpen/Drawings_MultipleViewPlacementBuilder.hxx
//#include <NXOpen/Drawings_OrderManager.hxx
//#include <NXOpen/Drawings_OrientationViewStyle.hxx
//#include <NXOpen/Drawings_OrientedSectionLine.hxx
//#include <NXOpen/Drawings_OrientedSectionLineBuilder.hxx
//#include <NXOpen/Drawings_OvtBuilder.hxx
//#include <NXOpen/Drawings_ParentViewBuilder.hxx
//#include <NXOpen/Drawings_PerspectiveViewStyle.hxx
//#include <NXOpen/Drawings_PictorialSectionLine.hxx
//#include <NXOpen/Drawings_PointAndAngleSectionLine.hxx
//#include <NXOpen/Drawings_PointAndAngleSectionLineBuilder.hxx
//#include <NXOpen/Drawings_PointToPointSectionLine.hxx
//#include <NXOpen/Drawings_PointToPointSectionLineBuilder.hxx
//#include <NXOpen/Drawings_ProjectedView.hxx
//#include <NXOpen/Drawings_ProjectedViewBuilder.hxx
//#include <NXOpen/Drawings_ProjectedViewOrientationBuilder.hxx
//#include <NXOpen/Drawings_ProjectedViewStyle.hxx
//#include <NXOpen/Drawings_RefineDisplayBuilder.hxx
//#include <NXOpen/Drawings_RemoveObjectsBuilder.hxx
//#include <NXOpen/Drawings_RenderSet.hxx
//#include <NXOpen/Drawings_ReportBuilder.hxx
//#include <NXOpen/Drawings_RevolvedSectionLine.hxx
//#include <NXOpen/Drawings_RevolvedSectionLineBuilder.hxx
//#include <NXOpen/Drawings_SecondaryGeometryInViewsBuilder.hxx
//#include <NXOpen/Drawings_SectionInViewBuilder.hxx
#include <NXOpen/Drawings_SectionLine.hxx>
#include <NXOpen/Drawings_SectionLineBuilder.hxx>
#include <NXOpen/Drawings_SectionLineCollection.hxx>
//#include <NXOpen/Drawings_SectionLineSegmentBuilder.hxx
//#include <NXOpen/Drawings_SectionLineSegmentBuilderList.hxx
//#include <NXOpen/Drawings_SectionLineSegmentPointBuilder.hxx
//#include <NXOpen/Drawings_SectionLineSegmentPointListBuilder.hxx
//#include <NXOpen/Drawings_SectionLineSegmentsBuilder.hxx
//#include <NXOpen/Drawings_SectionLineSettingsBuilder.hxx
//#include <NXOpen/Drawings_SectionLineStyleBuilder.hxx
#include <NXOpen/Drawings_SectionView.hxx>
#include <NXOpen/Drawings_SectionViewBuilder.hxx>
#include <NXOpen/Drawings_SectionViewStyle.hxx>
//#include <NXOpen/Drawings_SelectDraftingView.hxx>
//#include <NXOpen/Drawings_SelectDraftingViewList.hxx
//#include <NXOpen/Drawings_SelectDrawingRegion.hxx
//#include <NXOpen/Drawings_SelectDrawingView.hxx
//#include <NXOpen/Drawings_SelectDrawingViewList.hxx
//#include <NXOpen/Drawings_SelectModelViewBuilder.hxx
//#include <NXOpen/Drawings_SelectRegionBuilder.hxx
//#include <NXOpen/Drawings_SelectSectionLine.hxx
//#include <NXOpen/Drawings_SettingsBuilder.hxx
//#include <NXOpen/Drawings_ShadingViewStyle.hxx
//#include <NXOpen/Drawings_SheetBorderSettingsBuilder.hxx
//#include <NXOpen/Drawings_SheetDraftingViewCollection.hxx
//#include <NXOpen/Drawings_SheetMarginSettingsBuilder.hxx
//#include <NXOpen/Drawings_SheetSectionLineCollection.hxx
//#include <NXOpen/Drawings_SheetTemplateManager.hxx
//#include <NXOpen/Drawings_SheetZoneReferenceBuilder.hxx
//#include <NXOpen/Drawings_SheetZoneSettingsBuilder.hxx
#include <NXOpen/Drawings_ShipbuildingLinesViewStyle.hxx>
#include <NXOpen/Drawings_ShipDraftingViewLinesBuilder.hxx>
#include <NXOpen/Drawings_ShipDraftingViewLinesBuilderList.hxx>
#include <NXOpen/Drawings_ShipDraftingViewLinesViewStyle.hxx>
//#include <NXOpen/Drawings_SketchedHalfSectionLine.hxx
//#include <NXOpen/Drawings_SketchedPointToPointSectionLine.hxx
//#include <NXOpen/Drawings_SketchedSteppedSectionLine.hxx
//#include <NXOpen/Drawings_SketchSectionLineBuilder.hxx
#include <NXOpen/Drawings_SmoothEdgesViewStyle.hxx>
//#include <NXOpen/Drawings_SpecifySectionLineBuilder.hxx
//#include <NXOpen/Drawings_StandardViewsBuilder.hxx
#include <NXOpen/Drawings_SteppedSectionLine.hxx>
//#include <NXOpen/Drawings_SteppedSectionLineBuilder.hxx
//#include <NXOpen/Drawings_SvtBuilder.hxx
//#include <NXOpen/Drawings_ThreadsViewStyle.hxx
//#include <NXOpen/Drawings_TraceLinesViewStyle.hxx
//#include <NXOpen/Drawings_TrackDrawingChangesGeneralBuilder.hxx
//#include <NXOpen/Drawings_TrackDrawingChangesReportFilterBuilder.hxx
//#include <NXOpen/Drawings_UpdateViewsBuilder.hxx
//#include <NXOpen/Drawings_View2dOrientBuilder.hxx
//#include <NXOpen/Drawings_ViewAlignment.hxx
//#include <NXOpen/Drawings_ViewAlignmentBuilder.hxx
//#include <NXOpen/Drawings_ViewAlignmentCollection.hxx
//#include <NXOpen/Drawings_ViewBoundaryBuilder.hxx
#include <NXOpen/Drawings_ViewBreak.hxx>
#include <NXOpen/Drawings_ViewBreakBuilder.hxx>
//#include <NXOpen/Drawings_ViewBreakCollection.hxx
//#include <NXOpen/Drawings_ViewCenterCoordinateBuilder.hxx
//#include <NXOpen/Drawings_ViewCommonViewLabelBuilder.hxx
//#include <NXOpen/Drawings_ViewCopyTo3dBuilder.hxx
//#include <NXOpen/Drawings_ViewCreationWizardBuilder.hxx
//#include <NXOpen/Drawings_ViewDetailLabelBuilder.hxx
//#include <NXOpen/Drawings_ViewingDirectionArrow.hxx
//#include <NXOpen/Drawings_ViewingDirectionArrowLabel.hxx
//#include <NXOpen/Drawings_ViewLabelBuilder.hxx
//#include <NXOpen/Drawings_ViewLabelPreferencesData.hxx
//#include <NXOpen/Drawings_ViewOrientationBuilder.hxx
//#include <NXOpen/Drawings_ViewPlacementBuilder.hxx
//#include <NXOpen/Drawings_ViewProjectedArrowSettingsBuilder.hxx
//#include <NXOpen/Drawings_ViewProjectedLabelBuilder.hxx
//#include <NXOpen/Drawings_ViewProjectedViewSettingsBuilder.hxx
//#include <NXOpen/Drawings_ViewProjectionBuilder.hxx
//#include <NXOpen/Drawings_ViewProjectionPlaneBuilder.hxx
//#include <NXOpen/Drawings_ViewScaleBuilder.hxx
//#include <NXOpen/Drawings_ViewSectionLabelBuilder.hxx>
#include <NXOpen/Drawings_ViewSectionLineBuilder.hxx>
//#include <NXOpen/Drawings_ViewSettingsBuilder.hxx
#include <NXOpen/Drawings_ViewStyle.hxx>
//#include <NXOpen/Drawings_ViewStyleBaseBuilder.hxx
#include <NXOpen/Drawings_ViewStyleBuilder.hxx>
//#include <NXOpen/Drawings_ViewStyleDetailBuilder.hxx
#include <NXOpen/Drawings_ViewStyleFPCalloutConfigBuilder.hxx>
#include <NXOpen/Drawings_ViewStyleFPCalloutsBuilder.hxx>
#include <NXOpen/Drawings_ViewStyleFPCurvesBuilder.hxx>
#include <NXOpen/Drawings_ViewStyleGeneralBuilder.hxx>
#include <NXOpen/Drawings_ViewStyleHiddenLinesBuilder.hxx>
#include <NXOpen/Drawings_ViewStyleInheritPmiBuilder.hxx>
//#include <NXOpen/Drawings_ViewStyleOrientationBuilder.hxx
//#include <NXOpen/Drawings_ViewStylePerspectiveBuilder.hxx
//#include <NXOpen/Drawings_ViewStyleProjectedBuilder.hxx
//#include <NXOpen/Drawings_ViewStyleSecondaryComponentsBuilder.hxx
//#include <NXOpen/Drawings_ViewStyleSectionBuilder.hxx
//#include <NXOpen/Drawings_ViewStyleSectionConstraintsBuilder.hxx
//#include <NXOpen/Drawings_ViewStyleShadingBuilder.hxx
#include <NXOpen/Drawings_ViewStyleShipbuildingLinesBuilder.hxx>
#include <NXOpen/Drawings_ViewStyleShipbuildingLinesBuilderList.hxx>
//#include <NXOpen/Drawings_ViewStyleSmoothEdgesBuilder.hxx
//#include <NXOpen/Drawings_ViewStyleThreadsBuilder.hxx
//#include <NXOpen/Drawings_ViewStyleTraceLinesBuilder.hxx
//#include <NXOpen/Drawings_ViewStyleVirtualIntersectionsBuilder.hxx
#include <NXOpen/Drawings_ViewStyleVisibleLinesBuilder.hxx>
//#include <NXOpen/Drawings_ViewWorkflowBuilder.hxx
#include <NXOpen/Drawings_VirtualIntersectionsViewStyle.hxx>
#include <NXOpen/Drawings_VisibleAndHiddenLinesColorFontWidthBuilder.hxx>
#include <NXOpen/Drawings_VisibleLinesViewStyle.hxx>
//#include <NXOpen/Drawings_VisualDrawingComparePrefsBuilder.hxx
//#include <NXOpen/DrawingUtils.hxx
//#include <NXOpen/DxfdwgCreator.hxx
//#include <NXOpen/DxfdwgImporter.hxx
//#include <NXOpen/ErrorInfo.hxx
//#include <NXOpen/ErrorList.hxx
//#include <NXOpen/ExpDebugSession.hxx
//#include <NXOpen/FileNew.hxx
#include <NXOpen/FontCollection.hxx>
#include <NXOpen/Layer.hxx>
#include <NXOpen/Layer_Category.hxx>
#include <NXOpen/Layer_CategoryCollection.hxx>
#include <NXOpen/Layer_LayerManager.hxx>
#include <NXOpen/Layer_StateCollection.hxx>
#include <NXOpen/libnxopencpp_annotations_exports.hxx>
//#include <NXOpen/libnxopencpp_drafting_exports.hxx
//#include <NXOpen/libnxopencpp_drawings_exports.hxx
//#include <NXOpen/libnxopencpp_exports.hxx
//#include <NXOpen/libnxopencpp_gateway_exports.hxx
//#include <NXOpen/libnxopencpp_openxml_exports.hxx>
//#include <NXOpen/libnxopencpp_options_exports.hxx>
#include <NXOpen/libnxopencpp_pdm_exports.hxx>
//#include <NXOpen/libnxopencpp_preferences_exports.hxx
//#include <NXOpen/libnxopendebugsessioncpp_exports.hxx
//#include <NXOpen/libnxopendebuguicpp_exports.hxx
//#include <NXOpen/libnxopenjamtestcpp_exports.hxx
//#include <NXOpen/libnxopenuicpp_exports.hxx
//#include <NXOpen/libpidopencpp_exports.hxx
//#include <NXOpen/LogFile.hxx
//#include <NXOpen/ListCreator.hxx
//#include <NXOpen/ListCreatorList.hxx
//#include <NXOpen/ListingWindow.hxx
//#include <NXOpen/MenuBar_ContextMenu.hxx
//#include <NXOpen/MenuBar_ContextMenuEntry.hxx
//#include <NXOpen/MenuBar_ContextMenuProperties.hxx
//#include <NXOpen/MenuBar_MenuBarManager.hxx
//#include <NXOpen/MenuBar_MenuButton.hxx
//#include <NXOpen/MenuBar_MenuButtonEvent.hxx
#include <NXOpen/NXColor.hxx>
#include <NXOpen/NXException.hxx>
//#include <NXOpen/NXObject.hxx
//#include <NXOpen/NXObjectList.hxx
#include <NXOpen/NXObjectManager.hxx>
//#include <NXOpen/NXString.hxx
//#include <NXOpen/ObjectGeneralPropertiesBuilder.hxx
//#include <NXOpen/ObjectList.hxx
//#include <NXOpen/ObjectSelector.hxx
//#include <NXOpen/ObjectTypeSelector.hxx
//#include <NXOpen/OpenXml_DocumentData.hxx>
//#include <NXOpen/OpenXml_DocumentDataGroup.hxx>
//#include <NXOpen/OpenXml_ImageDocumentData.hxx>
//#include <NXOpen/OpenXml_ImageGroupDocumentData.hxx>
//#include <NXOpen/OpenXml_TableCellData.hxx>
//#include <NXOpen/OpenXml_TableDocumentData.hxx>
//#include <NXOpen/OpenXml_TextDocumentData.hxx>
//#include <NXOpen/Options_DraftingStandardChangeList.hxx>
#include <NXOpen/Options_OptionsManager.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/Preferences_AnnotationPreferences.hxx>
//#include <NXOpen/Preferences_BaseViewPreferences.hxx
#include <NXOpen/Preferences_DetailViewPreferences.hxx>
#include <NXOpen/Preferences_DraftingPreferenceManager.hxx>
//#include <NXOpen/Preferences_FlatPatternViewPreferences.hxx
#include <NXOpen/Preferences_GeneralViewPreferences.hxx>
#include <NXOpen/Preferences_HiddenLinesViewPreferences.hxx>
//#include <NXOpen/Preferences_IBaseViewPreferences.hxx
//#include <NXOpen/Preferences_IDetailViewPreferences.hxx
//#include <NXOpen/Preferences_IGeneralViewPreferences.hxx
//#include <NXOpen/Preferences_IHiddenLinesViewPreferences.hxx
#include <NXOpen/Preferences_InheritPmiPreferences.hxx>
//#include <NXOpen/Preferences_IOrientationViewPreferences.hxx
//#include <NXOpen/Preferences_IPerspectiveViewPreferences.hxx
//#include <NXOpen/Preferences_IProjectedViewPreferences.hxx
//#include <NXOpen/Preferences_ISectionViewPreferences.hxx
//#include <NXOpen/Preferences_IShadingViewPreferences.hxx
//#include <NXOpen/Preferences_ISmoothEdgesViewPreferences.hxx
//#include <NXOpen/Preferences_IThreadsViewPreferences.hxx
//#include <NXOpen/Preferences_ITraceLinesViewPreferences.hxx
//#include <NXOpen/Preferences_IVirtualIntersectionsViewPreferences.hxx
//#include <NXOpen/Preferences_IVisibleLinesViewPreferences.hxx
#include <NXOpen/Preferences_LoadDraftingStandardBuilder.hxx>
#include <NXOpen/Preferences_ObjectPreferences.hxx>
//#include <NXOpen/Preferences_PartAeroSheetmetal.hxx
#include <NXOpen/Preferences_PartDrafting.hxx>
//#include <NXOpen/Preferences_PartFlexiblePrintedCircuitDesign.hxx
//#include <NXOpen/Preferences_PartModeling.hxx
#include <NXOpen/Preferences_PartObject.hxx>
#include <NXOpen/Preferences_PartPreferences.hxx>
//#include <NXOpen/Preferences_PartSheetmetal.hxx
//#include <NXOpen/Preferences_PartSketch.hxx
//#include <NXOpen/Preferences_PartUserInterface.hxx
#include <NXOpen/Preferences_PartVisualizationColorSetting.hxx>
#include <NXOpen/Preferences_PartVisualizationEmphasis.hxx>
#include <NXOpen/Preferences_PartVisualizationLine.hxx>
#include <NXOpen/Preferences_PartVisualizationNamesBorders.hxx>
#include <NXOpen/Preferences_PartVisualizationPerformance.hxx>
#include <NXOpen/Preferences_PartVisualizationScreen.hxx>
#include <NXOpen/Preferences_PartVisualizationShade.hxx>
#include <NXOpen/Preferences_PartVisualizationVisual.hxx>
//#include <NXOpen/Preferences_PostProcessing.hxx
//#include <NXOpen/Preferences_ProjectedViewPreferences.hxx
//#include <NXOpen/Preferences_RoutingApplicationView.hxx
//#include <NXOpen/Preferences_RoutingCharacteristics.hxx
//#include <NXOpen/Preferences_RoutingElectrical.hxx
//#include <NXOpen/Preferences_RoutingLogical.hxx
//#include <NXOpen/Preferences_RoutingMechanical.hxx
//#include <NXOpen/Preferences_RoutingPart.hxx
//#include <NXOpen/Preferences_RoutingPartLibrary.hxx
//#include <NXOpen/Preferences_RoutingPath.hxx
//#include <NXOpen/Preferences_RoutingStock.hxx
//#include <NXOpen/Preferences_RoutingUserPreferences.hxx
//#include <NXOpen/Preferences_RulePreferences.hxx
#include <NXOpen/Preferences_SectionViewPreferences.hxx>
#include <NXOpen/Preferences_SessionAssemblies.hxx>
#include <NXOpen/Preferences_SessionDrafting.hxx>
//#include <NXOpen/Preferences_SessionMeasureRequirements.hxx
//#include <NXOpen/Preferences_SessionModeling.hxx
//#include <NXOpen/Preferences_SessionNXGateway.hxx
#include <NXOpen/Preferences_SessionPdm.hxx>
#include <NXOpen/Preferences_SessionPmi.hxx>
#include <NXOpen/Preferences_SessionPreferences.hxx>
//#include <NXOpen/Preferences_SessionSketch.hxx
//#include <NXOpen/Preferences_SessionUserInterface.hxx
//#include <NXOpen/Preferences_SessionUserInterfaceUI.hxx
#include <NXOpen/Preferences_SessionVisualizationColorSetting.hxx>
#include <NXOpen/Preferences_SessionVisualizationEmphasis.hxx>
#include <NXOpen/Preferences_SessionVisualizationHighEndRendering.hxx>
#include <NXOpen/Preferences_SessionVisualizationHighQualityImage.hxx>
#include <NXOpen/Preferences_SessionVisualizationPerformance.hxx>
#include <NXOpen/Preferences_SessionVisualizationScreen.hxx>
#include <NXOpen/Preferences_SessionVisualizationShade.hxx>
#include <NXOpen/Preferences_SessionVisualizationSpecialEffects.hxx>
#include <NXOpen/Preferences_SessionVisualizationVisual.hxx>
//#include <NXOpen/Preferences_SessionWorkPlane.hxx
#include <NXOpen/Preferences_ShadingViewPreferences.hxx>
#include <NXOpen/Preferences_ShipbuildingLinesViewPreferences.hxx>
#include <NXOpen/Features_ShipDesign_ReferenceLine.hxx>
#include <NXOpen/Features_ShipDesign_ReferenceLineBuilder.hxx>
#include <NXOpen/Features_ShipDesign_MarkingLine.hxx>
#include <NXOpen/Features_ShipDesign_MarkingLineBuilder.hxx>
//#include <NXOpen/Preferences_ShipDraftingViewLinesViewPreferences.hxx
//#include <NXOpen/Preferences_SketchPreferences.hxx
#include <NXOpen/Preferences_SmoothEdgesViewPreferences.hxx>
//#include <NXOpen/Preferences_SubdivisionModelingPreferences.hxx
#include <NXOpen/Preferences_ThreadsViewPreferences.hxx>
#include <NXOpen/Preferences_TraceLinesViewPreferences.hxx>
#include <NXOpen/Preferences_ViewPreferences.hxx>
//#include <NXOpen/Preferences_ViewSection.hxx
#include <NXOpen/Preferences_ViewStylePreferencesData.hxx>
#include <NXOpen/Preferences_ViewVisualizationSpecialEffects.hxx>
#include <NXOpen/Preferences_ViewVisualizationVisual.hxx>
#include <NXOpen/Preferences_VirtualIntersectionsViewPreferences.hxx>
#include <NXOpen/Preferences_VisibleLinesViewPreferences.hxx>
#include <NXOpen/Preferences_VisualizationFonts.hxx>
#include <NXOpen/Preferences_VisualizationHandles.hxx>
#include <NXOpen/Preferences_VisualizationLine.hxx>
//#include <NXOpen/Preferences_WorkPlane.hxx
//#include <NXOpen/PreviewPropertiesBuilder.hxx
//#include <NXOpen/PropertiesManager.hxx
//#include <NXOpen/PropertyContainer.hxx
//#include <NXOpen/ResourceBarManager.hxx
#include <NXOpen/Session.hxx>
#include <NXOpen/Sketch.hxx>
//#include <NXOpen/Spreadsheet.hxx
//#include <NXOpen/SpreadsheetCellData.hxx
//#include <NXOpen/SpreadsheetExternal.hxx
//#include <NXOpen/SpreadsheetManager.hxx
//#include <NXOpen/TaggedObject.hxx
//#include <NXOpen/TaggedObjectCollection.hxx
//#include <NXOpen/TaggedObjectList.hxx
//#include <NXOpen/type.hxx
//#include <NXOpen/ugmath.hxx
//#include <NXOpen/UI.hxx
//#include <NXOpen/UI.hxx
//#include <NXOpen/UIStyler_Attachment.hxx
//#include <NXOpen/UIStyler_BitMap.hxx
//#include <NXOpen/UIStyler_ButtonLayout.hxx
//#include <NXOpen/UIStyler_CollapsibleGroup.hxx
#include <NXOpen/UIStyler_ColorTool.hxx>
//#include <NXOpen/UIStyler_Dialog.hxx
//#include <NXOpen/UIStyler_DialogItem.hxx
//#include <NXOpen/UIStyler_FileOperationData.hxx
//#include <NXOpen/UIStyler_GroupBox.hxx
//#include <NXOpen/UIStyler_IntegerItem.hxx
//#include <NXOpen/UIStyler_IntegerScale.hxx
//#include <NXOpen/UIStyler_LabelItem.hxx
//#include <NXOpen/UIStyler_MultiSelectList.hxx
//#include <NXOpen/UIStyler_MultiTextBox.hxx
//#include <NXOpen/UIStyler_OptionMenu.hxx>
//#include <NXOpen/UIStyler_OptionToggle.hxx>
//#include <NXOpen/UIStyler_PageSwitchData.hxx
//#include <NXOpen/UIStyler_PropertyPage.hxx
//#include <NXOpen/UIStyler_PushButton.hxx
//#include <NXOpen/UIStyler_RadioBox.hxx
//#include <NXOpen/UIStyler_RealItem.hxx
//#include <NXOpen/UIStyler_RealScale.hxx
//#include <NXOpen/UIStyler_RowColumn.hxx
//#include <NXOpen/UIStyler_ScrolledWindow.hxx
//#include <NXOpen/UIStyler_SelectionBox.hxx
//#include <NXOpen/UIStyler_Separator.hxx
//#include <NXOpen/UIStyler_SingleSelectList.hxx
//#include <NXOpen/UIStyler_StringItem.hxx
//#include <NXOpen/UIStyler_Styler.hxx
//#include <NXOpen/UIStyler_StylerEvent.hxx
//#include <NXOpen/UIStyler_StylerItem.hxx
//#include <NXOpen/UIStyler_TabControl.hxx
//#include <NXOpen/UIStyler_Toggle.hxx
//#include <NXOpen/UIStyler_ToolPalette.hxx
//#include <NXOpen/UIStyler_WideString.hxx
//#include <NXOpen/UITemplateTestManager.hxx
#include <NXOpen/Unit.hxx>
#include <NXOpen/UnitCollection.hxx>
//#include <NXOpen/Update.hxx
#include <NXOpen/View.hxx>
#include <NXOpen/ViewCollection.hxx>
#include <NXOpen/ViewDependentDisplayManager.hxx>
#include <NXOpen/ViewUIManager.hxx>
//#include <NXOpen/WidthDefinition.hxx
//#include <NXOpen/WindowHandle.hxx
//#include <NXOpen/Xform.hxx
//#include <NXOpen/XformCollection.hxx